In [1]:
import pandas as pd

In [3]:
bike_data = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Bike_Data.xlsx" )

In [4]:
bike_data.head(5)

,Region,Country,Customer,Business Segment,Category,Model,Color,SalesDate,ListPrice,UnitPrice,OrderQty
0,North America,United States,Professional Containers and Packaging Co.,Clothing,Tights,Women's Tights,Black,2018-08-22,74.99,44.99,1
1,North America,United States,Professional Containers and Packaging Co.,Clothing,Gloves,Full-Finger Gloves,Black,2018-08-17,37.99,22.79,2
2,North America,United States,Professional Containers and Packaging Co.,Bikes,Mountain Bikes,Mountain-200,Black,2018-08-14,2294.99,1229.46,1
3,North America,United States,Professional Containers and Packaging Co.,Clothing,Jerseys,Long-Sleeve Logo Jersey,Multi,2018-08-13,49.99,28.84,6
4,North America,United States,Professional Containers and Packaging Co.,Clothing,Gloves,Full-Finger Gloves,Black,2018-08-09,37.99,22.79,4

In [5]:
bike_data.columns

Index(['Region', 'Country', 'Customer', 'Business Segment', 'Category',
       'Model', 'Color', 'SalesDate', 'ListPrice', 'UnitPrice', 'OrderQty'],
      dtype='object')

In [7]:
bike_data.shape

(60920, 11)

In [8]:
bike_data.dtypes

Region                      object
Country                     object
Customer                    object
Business Segment            object
Category                    object
Model                       object
Color                       object
SalesDate           datetime64[ns]
ListPrice                  float64
UnitPrice                  float64
OrderQty                     int64
dtype: object

#### want to create a New columns in the table 
#### 1) sales = Listprice * UnitPrice
#### 2) Cost = unitprice * Orderqty
#### 3) Profit = Sales - Cost

#### 3 columns need to add as  a Data ENgineer

In [16]:
bike_data['Cost'] = bike_data['UnitPrice'] * bike_data['OrderQty'] # 1) sales = Listprice * Unitprice
bike_data['Sales'] = bike_data['ListPrice'] * bike_data['OrderQty'] # 2) Cost = unitprice * Orderqty
bike_data['Profit'] = bike_data['Sales'] * bike_data['Cost']  # 3) Profit = Sales - Cost¶

In [17]:
bike_data.shape

(60920, 14)

In [18]:
bike_data.head(3)

,Region,Country,Customer,Business Segment,Category,Model,Color,SalesDate,ListPrice,UnitPrice,OrderQty,Cost,Sales,Profit
0,North America,United States,Professional Containers and Packaging Co.,Clothing,Tights,Women's Tights,Black,2018-08-22,74.99,44.99,1,44.99,74.99,3.373800e+03
1,North America,United States,Professional Containers and Packaging Co.,Clothing,Gloves,Full-Finger Gloves,Black,2018-08-17,37.99,22.79,2,45.58,75.98,3.463168e+03
2,North America,United States,Professional Containers and Packaging Co.,Bikes,Mountain Bikes,Mountain-200,Black,2018-08-14,2294.99,1229.46,1,1229.46,2294.99,2.821598e+06

In [19]:
bike_data.groupby("Business Segment")[["Sales"]].sum().head(5)  # rarely used this method for single column

                         Sales
Business Segment
Accessories       9.937876e+05
Bikes             1.166650e+08
Clothing          3.082793e+06
Components        2.033570e+07
Electric Bikes    2.500000e+03

In [21]:
bike_data.groupby("Business Segment").agg({"Sales":"sum"}).head(5) # above method can also written like this  for Multiple columns

                         Sales
Business Segment
Accessories       9.937876e+05
Bikes             1.166650e+08
Clothing          3.082793e+06
Components        2.033570e+07
Electric Bikes    2.500000e+03

In [23]:
bike_data.groupby("Business Segment").agg(Total_Sales = ("Sales","sum")).head(5)    # to avoid renaming column

                   Total_Sales
Business Segment
Accessories       9.937876e+05
Bikes             1.166650e+08
Clothing          3.082793e+06
Components        2.033570e+07
Electric Bikes    2.500000e+03

In [63]:
emp = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Emp1.csv"  , encoding = "ISO-8859-1") 
# encoding is to convert the file format

In [39]:
emp.head(6)

,EmployeeID,ManagerID,Title,MaritalStatus,Gender,HireDate,Dept,JobGrade
0,1,16,Gustavo Achong,M,M,02-02-2013 00:00,Sales,Admin
1,2,6,Catherine Abel,S,M,31-08-2013 00:00,Sales,Management
2,3,12,Kim Abercrombie,M,M,16-06-2014 00:00,Finance,Admin
3,4,3,Humberto Acevedo,S,M,10-07-2014 00:00,Logistics,Admin
4,5,263,Pilar Ackerman,M,M,16-07-2014 00:00,Human Resource,Admin
5,6,109,Frances Adams,S,M,25-07-2014 00:00,Sales,Management

In [40]:
emp.shape

(50, 8)

In [41]:
emp.columns

Index(['EmployeeID', 'ManagerID', 'Title', 'MaritalStatus', 'Gender',
       'HireDate', 'Dept', 'JobGrade'],
      dtype='object')

In [42]:
emp.dtypes

EmployeeID        int64
ManagerID         int64
Title            object
MaritalStatus    object
Gender           object
HireDate         object
Dept             object
JobGrade         object
dtype: object

In [47]:
# find the department wise count
emp.groupby("Dept").agg(Total_Emp = ("EmployeeID" ,"count")).reset_index()

             Dept  Total_Emp
0         Finance         11
1  Human Resource          6
2       Logistics          8
3      Production         14
4           Sales         11

In [49]:
# Maritial_status
# M = Married
# S = Single

#gender
# M = Male 
# F = Female 

#1) Married Male (g1)
#2) Married Female (g2)
#3) Single Male (g3)
#4) Single Female (g4)

In [50]:
emp.groupby(['MaritalStatus' ,'Gender'])[['EmployeeID']].count()

                      EmployeeID
MaritalStatus Gender
M             F                7
              M               15
S             F                6
              M               22

In [ ]:
# writing functions

In [64]:
def F_Marital_status(a):
    if a == "M":
        return "Married"
    elif a == 'S':
        return "Single"
    else: 
        return "Unknown"

In [53]:
F_Marital_status("b")

'Unknown'

In [65]:
def F_Gender_status(a):
    if a == "M":
        return "Male"
    elif a == 'F':
        return "Female"
    else: 
        return "Unknown"

In [56]:
F_Gender_status("M")

'Male'

In [66]:
emp.head(5)

,EmployeeID,ManagerID,Title,MaritalStatus,Gender,HireDate,Dept,JobGrade
0,1,16,Gustavo Achong,M,M,02-02-2013 00:00,Sales,Admin
1,2,6,Catherine Abel,S,M,31-08-2013 00:00,Sales,Management
2,3,12,Kim Abercrombie,M,M,16-06-2014 00:00,Finance,Admin
3,4,3,Humberto Acevedo,S,M,10-07-2014 00:00,Logistics,Admin
4,5,263,Pilar Ackerman,M,M,16-07-2014 00:00,Human Resource,Admin

In [59]:
emp['MaritalStatus1'] = emp['MaritalStatus'].apply(F_Marital_status)
emp['Gender1'] = emp['Gender'].apply(F_Gender_status)                  # by this way new column is created

In [60]:
emp.head(5)

,EmployeeID,ManagerID,Title,MaritalStatus,Gender,HireDate,Dept,JobGrade,MaritalStatus1,Gender1
0,1,16,Gustavo Achong,M,M,02-02-2013 00:00,Sales,Admin,Married,Male
1,2,6,Catherine Abel,S,M,31-08-2013 00:00,Sales,Management,Single,Male
2,3,12,Kim Abercrombie,M,M,16-06-2014 00:00,Finance,Admin,Married,Male
3,4,3,Humberto Acevedo,S,M,10-07-2014 00:00,Logistics,Admin,Single,Male
4,5,263,Pilar Ackerman,M,M,16-07-2014 00:00,Human Resource,Admin,Married,Male

In [62]:
emp.shape

(50, 10)

In [67]:
emp.head(5)

,EmployeeID,ManagerID,Title,MaritalStatus,Gender,HireDate,Dept,JobGrade
0,1,16,Gustavo Achong,M,M,02-02-2013 00:00,Sales,Admin
1,2,6,Catherine Abel,S,M,31-08-2013 00:00,Sales,Management
2,3,12,Kim Abercrombie,M,M,16-06-2014 00:00,Finance,Admin
3,4,3,Humberto Acevedo,S,M,10-07-2014 00:00,Logistics,Admin
4,5,263,Pilar Ackerman,M,M,16-07-2014 00:00,Human Resource,Admin

In [68]:
emp['MaritalStatus'] = emp['MaritalStatus'].apply(F_Marital_status)
emp['Gender'] = emp['Gender'].apply(F_Gender_status)

In [69]:
emp.head(5)

,EmployeeID,ManagerID,Title,MaritalStatus,Gender,HireDate,Dept,JobGrade
0,1,16,Gustavo Achong,Married,Male,02-02-2013 00:00,Sales,Admin
1,2,6,Catherine Abel,Single,Male,31-08-2013 00:00,Sales,Management
2,3,12,Kim Abercrombie,Married,Male,16-06-2014 00:00,Finance,Admin
3,4,3,Humberto Acevedo,Single,Male,10-07-2014 00:00,Logistics,Admin
4,5,263,Pilar Ackerman,Married,Male,16-07-2014 00:00,Human Resource,Admin

In [70]:
emp.groupby("Dept").agg(Total_Emp = ("EmployeeID" ,"count")).reset_index()

             Dept  Total_Emp
0         Finance         11
1  Human Resource          6
2       Logistics          8
3      Production         14
4           Sales         11

In [72]:
emp.groupby(['MaritalStatus' ,'Gender'])[['EmployeeID']].count().reset_index()

  MaritalStatus  Gender  EmployeeID
0       Married  Female           7
1       Married    Male          15
2        Single  Female           6
3        Single    Male          22

In [73]:
bike_data.head(5)

,Region,Country,Customer,Business Segment,Category,Model,Color,SalesDate,ListPrice,UnitPrice,OrderQty,Cost,Sales,Profit
0,North America,United States,Professional Containers and Packaging Co.,Clothing,Tights,Women's Tights,Black,2018-08-22,74.99,44.99,1,44.99,74.99,3.373800e+03
1,North America,United States,Professional Containers and Packaging Co.,Clothing,Gloves,Full-Finger Gloves,Black,2018-08-17,37.99,22.79,2,45.58,75.98,3.463168e+03
2,North America,United States,Professional Containers and Packaging Co.,Bikes,Mountain Bikes,Mountain-200,Black,2018-08-14,2294.99,1229.46,1,1229.46,2294.99,2.821598e+06
3,North America,United States,Professional Containers and Packaging Co.,Clothing,Jerseys,Long-Sleeve Logo Jersey,Multi,2018-08-13,49.99,28.84,6,173.04,299.94,5.190162e+04
4,North America,United States,Professional Containers and Packaging Co.,Clothing,Gloves,Full-Finger Gloves,Black,2018-08-09,37.99,22.79,4,91.16,151.96,1.385267e+04

In [ ]:
# assignment
# write a sales function
# any sales < 5000 ---Bronze
# sales 5 k - 10k ----silver
# sales 10k - 15k ----gold
# > 15k           ----platinum

# in bike data one additional column need to add sales group

In [74]:
bike_data.shape

(60920, 14)

In [76]:
def trans_grp(a):
    if a < 5000:
        return "Bronze"
    elif a > 5000 and a < 10000:
        return "Silver"
    elif a > 10000 and a < 15000:
        return "Gold"
    else:
        return "Platinum"

In [77]:
bike_data['Sales_group'] = bike_data['Sales'].apply(trans_grp)

In [78]:
bike_data.shape

(60920, 15)

In [80]:
bike_data.head(5)

,Region,Country,Customer,Business Segment,Category,Model,Color,SalesDate,ListPrice,UnitPrice,OrderQty,Cost,Sales,Profit,Sales_group
0,North America,United States,Professional Containers and Packaging Co.,Clothing,Tights,Women's Tights,Black,2018-08-22,74.99,44.99,1,44.99,74.99,3.373800e+03,Bronze
1,North America,United States,Professional Containers and Packaging Co.,Clothing,Gloves,Full-Finger Gloves,Black,2018-08-17,37.99,22.79,2,45.58,75.98,3.463168e+03,Bronze
2,North America,United States,Professional Containers and Packaging Co.,Bikes,Mountain Bikes,Mountain-200,Black,2018-08-14,2294.99,1229.46,1,1229.46,2294.99,2.821598e+06,Bronze
3,North America,United States,Professional Containers and Packaging Co.,Clothing,Jerseys,Long-Sleeve Logo Jersey,Multi,2018-08-13,49.99,28.84,6,173.04,299.94,5.190162e+04,Bronze
4,North America,United States,Professional Containers and Packaging Co.,Clothing,Gloves,Full-Finger Gloves,Black,2018-08-09,37.99,22.79,4,91.16,151.96,1.385267e+04,Bronze

In [81]:
bike_data.groupby("Sales_group")[["Region"]].count()

             Region
Sales_group
Bronze        53169
Gold           1683
Platinum       1057
Silver         5011

In [83]:
bike_data.groupby("Sales_group")[["Region"]].count().rename(columns={"Region":"TXN_Count"}).reset_index()

  Sales_group  TXN_Count
0      Bronze      53169
1        Gold       1683
2    Platinum       1057
3      Silver       5011