In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [40]:
cust_data = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\Cust_Data.xlsx")

In [3]:
cust_data.head(5)

   CustID  CustName   CustLoc  CustAge
0     1.0     Kiran      Pune     29.0
1     1.0     Kiran      Pune     29.0
2     2.0   Sathish  Maldives     30.0
3     3.0    Eshwar    Mumbai     34.0
4     5.0  Santhosh  Maldives     30.0

In [6]:
cust_data.shape

(8, 4)

In [7]:
list(cust_data.columns)

['CustID', 'CustName', 'CustLoc', 'CustAge']

In [9]:
print("The No of columns in given data set:" , cust_data.shape[1])

The No of columns in given data set: 4

In [10]:
print("The No of rows in given data set:" , cust_data.shape[0])

The No of rows in given data set: 8

In [11]:
cust_data.isna().sum()

CustID      1
CustName    2
CustLoc     1
CustAge     2
dtype: int64

In [12]:
(cust_data.isna().sum() / cust_data.shape[0]) * 100

CustID      12.5
CustName    25.0
CustLoc     12.5
CustAge     25.0
dtype: float64

In [13]:
cust_data.dtypes

CustID      float64
CustName     object
CustLoc      object
CustAge     float64
dtype: object

In [14]:
# in numpy this is the function which is used to find the numerical/int/float columns
list(cust_data.select_dtypes(include = np.number).columns)

['CustID', 'CustAge']

In [15]:
#categorical data 
list(cust_data.select_dtypes(exclude = np.number).columns)

['CustName', 'CustLoc']

In [23]:
cust_data.head(10)

   CustID  CustName    CustLoc  CustAge
0     1.0     Kiran       Pune     29.0
1     1.0     Kiran       Pune     29.0
2     2.0   Sathish   Maldives     30.0
3     3.0    Eshwar     Mumbai     34.0
4     5.0  Santhosh   Maldives     30.0
5     6.0    Mahesh   Tirupati     32.0
6     NaN       NaN        NaN      NaN
7     7.0       NaN  Bangalore      NaN

In [17]:
cust_data = cust_data.dropna() # which ever row had null value comple row will be dropped

In [18]:
cust_data.head(10)

   CustID  CustName   CustLoc  CustAge
0     1.0     Kiran      Pune     29.0
1     1.0     Kiran      Pune     29.0
2     2.0   Sathish  Maldives     30.0
3     3.0    Eshwar    Mumbai     34.0
4     5.0  Santhosh  Maldives     30.0
5     6.0    Mahesh  Tirupati     32.0

In [41]:
cust_data = cust_data.dropna(subset = 'CustID') # this will drop only if custid had Na value

In [42]:
cust_data.head(10)

   CustID  CustName    CustLoc  CustAge
0     1.0     Kiran       Pune     29.0
1     1.0     Kiran       Pune     29.0
2     2.0   Sathish   Maldives     30.0
3     3.0    Eshwar     Mumbai     34.0
4     5.0  Santhosh   Maldives     30.0
5     6.0    Mahesh   Tirupati     32.0
7     7.0       NaN  Bangalore      NaN

In [43]:
cust_data.shape

(7, 4)

In [56]:
cust_data = cust_data.drop_duplicates()

In [57]:
cust_data.shape

(6, 4)

In [52]:
cust_data['CustAge'] = cust_data['CustAge'].fillna(cust_data['CustAge'].mean()).astype("int")

In [53]:
cust_data.head(10)

   CustID  CustName    CustLoc  CustAge
0       1     Kiran       Pune       29
1       1     Kiran       Pune       29
2       2   Sathish   Maldives       30
3       3    Eshwar     Mumbai       34
4       5  Santhosh   Maldives       30
5       6    Mahesh   Tirupati       32
7       7  Guest/Na  Bangalore       30

In [54]:
cust_data['CustLoc'] = cust_data['CustLoc'].fillna(cust_data['CustLoc'].mode()[0]) #[0] is index

In [55]:
cust_data.head(10)

   CustID  CustName    CustLoc  CustAge
0       1     Kiran       Pune       29
1       1     Kiran       Pune       29
2       2   Sathish   Maldives       30
3       3    Eshwar     Mumbai       34
4       5  Santhosh   Maldives       30
5       6    Mahesh   Tirupati       32
7       7  Guest/Na  Bangalore       30

In [48]:
cust_data['CustName'] = cust_data['CustName'].fillna("Guest/Na")

In [49]:
cust_data.head(10)

   CustID  CustName    CustLoc  CustAge
0     1.0     Kiran       Pune       29
1     1.0     Kiran       Pune       29
2     2.0   Sathish   Maldives       30
3     3.0    Eshwar     Mumbai       34
4     5.0  Santhosh   Maldives       30
5     6.0    Mahesh   Tirupati       32
7     7.0  Guest/Na  Bangalore       30

In [50]:
cust_data['CustID'] = cust_data['CustID'].astype("int")

In [58]:
cust_data.head(10)

   CustID  CustName    CustLoc  CustAge
0       1     Kiran       Pune       29
2       2   Sathish   Maldives       30
3       3    Eshwar     Mumbai       34
4       5  Santhosh   Maldives       30
5       6    Mahesh   Tirupati       32
7       7  Guest/Na  Bangalore       30