In [61]:
import pandas as pd

In [62]:
import numpy as np  # later

In [24]:
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\Car_Data_1.csv")

In [25]:
data.head(5)    # NaN/ NaT is not a Value --- This represents a Missing Value

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014.0,3.35,5.59,27000.0,Petrol,Dealer,Manual,1st Owner
1,sx4,2013.0,4.75,9.54,43000.0,Diesel,Dealer,Manual,NaN
2,ciaz,2017.0,7.25,9.85,6900.0,Petrol,Dealer,Manual,NaN
3,wagon r,2011.0,2.85,4.15,5200.0,Petrol,Dealer,Manual,NaN
4,NaN,2014.0,4.60,6.87,42450.0,Diesel,Dealer,Manual,NaN

In [26]:
data.dtypes

Car_Name          object
Year             float64
Selling_Price    float64
Present_Price    float64
Kms_Driven       float64
Fuel_Type         object
Seller_Type       object
Transmission      object
Car_Owner         object
dtype: object

In [27]:
data.shape

(301, 9)

In [9]:
# Req 1 : Find the No of Missing Values of each Column

In [28]:
data.head(6)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014.0,3.35,5.59,27000.0,Petrol,Dealer,Manual,1st Owner
1,sx4,2013.0,4.75,9.54,43000.0,Diesel,Dealer,Manual,NaN
2,ciaz,2017.0,7.25,9.85,6900.0,Petrol,Dealer,Manual,NaN
3,wagon r,2011.0,2.85,4.15,5200.0,Petrol,Dealer,Manual,NaN
4,NaN,2014.0,4.60,6.87,42450.0,Diesel,Dealer,Manual,NaN
5,NaN,2018.0,9.25,9.83,2071.0,Diesel,Dealer,Manual,NaN

In [42]:
data.isna().head(5) # where NaN is there it is True/False

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,True
4,True,False,False,False,False,False,False,False,True

In [30]:
data.isna().head(5) # isna() is a function (binary -> True/False)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,True
4,True,False,False,False,False,False,False,False,True

In [31]:
data.isna().sum()  # will give count of missing Values count it is not ok we have to give it in percentage

Car_Name          18
Year              32
Selling_Price     44
Present_Price     51
Kms_Driven        70
Fuel_Type         35
Seller_Type       59
Transmission     241
Car_Owner         37
dtype: int64

In [32]:
data.isna().sum() /301

Car_Name         0.059801
Year             0.106312
Selling_Price    0.146179
Present_Price    0.169435
Kms_Driven       0.232558
Fuel_Type        0.116279
Seller_Type      0.196013
Transmission     0.800664
Car_Owner        0.122924
dtype: float64

In [33]:
(data.isna().sum()/301) * 100  # missing value percentage

Car_Name          5.980066
Year             10.631229
Selling_Price    14.617940
Present_Price    16.943522
Kms_Driven       23.255814
Fuel_Type        11.627907
Seller_Type      19.601329
Transmission     80.066445
Car_Owner        12.292359
dtype: float64

In [34]:
data.shape[0]

301

In [35]:
(data.isna().sum() / data.shape[0]) * 100  # missing value percentage

Car_Name          5.980066
Year             10.631229
Selling_Price    14.617940
Present_Price    16.943522
Kms_Driven       23.255814
Fuel_Type        11.627907
Seller_Type      19.601329
Transmission     80.066445
Car_Owner        12.292359
dtype: float64

In [ ]:
# DE --> one of the task will be (impute the missing Values)  --> (filling the null values)

In [38]:
# if you missing value percentage is more than 70 % ( simply drop the column)
# if the missing value percentage is less than 30% (impute it) fill the missing values
# if the missing value percentage is b/w 30 and 70 (check with clients / data re-share / suggest to correct the data)

In [37]:
# imputation means filling the NaN values with other values

In [52]:
# creating dict
data = {
'Name' : [ None , "Amar" , "Rahul" ,"Vishal"  , "Santosh"] ,
'Age' :  [25 , None , 30 , None , 28 ] ,
'Salary' : [5000, 6000 , None ,7000, 9000] ,
'Dept' : ["HR" , "IT" , "HR" , "IT" , None]
}

In [53]:
df = pd.DataFrame(data)

In [56]:
df.head(5) # here in name and dept it is coming as None instead of NaN

      Name   Age  Salary  Dept
0     None  25.0  5000.0    HR
1     Amar   NaN  6000.0    IT
2    Rahul  30.0     NaN    HR
3   Vishal   NaN  7000.0    IT
4  Santosh  28.0  9000.0  None

In [57]:
df.isna()

    Name    Age  Salary   Dept
0   True  False   False  False
1  False   True   False  False
2  False  False    True  False
3  False   True   False  False
4  False  False   False   True

In [58]:
df.isna().sum()

Name      1
Age       2
Salary    1
Dept      1
dtype: int64

In [59]:
# if None is wirking fine can proceed if not working conert as follows

In [79]:
data1 = {
'Name' : [ np.nan , "Amar" , "Rahul" ,"Vishal"  , "Santosh"] ,
'Age' :  [25 , None , 30 , None , 28 ] ,
'Salary' : [5000, 6000 , None ,7000, 90000] ,
'Dept' : ["HR" , "IT" , "HR" , "IT" , np.nan]
}

In [80]:
df = pd.DataFrame(data1)

In [81]:
df.isna().sum()

Name      1
Age       2
Salary    1
Dept      1
dtype: int64

In [82]:
df.isna()

    Name    Age  Salary   Dept
0   True  False   False  False
1  False   True   False  False
2  False  False    True  False
3  False   True   False  False
4  False  False   False   True

In [83]:
df.head(5)

      Name   Age   Salary Dept
0      NaN  25.0   5000.0   HR
1     Amar   NaN   6000.0   IT
2    Rahul  30.0      NaN   HR
3   Vishal   NaN   7000.0   IT
4  Santosh  28.0  90000.0  NaN

In [69]:
(df.isna().sum() / df.shape[0]) * 100

Name      20.0
Age       40.0
Salary    20.0
Dept      20.0
dtype: float64

In [71]:
# Few cusions 
# cousionA : 23
# cousionB : 24
# cousionC : 22
# cousionD : 24
# cousionE : 23 (this is my imputation ( this may be correct / may not be correct)
# imputation is average value 

# cousionA : 23
# cousionB : 24
# cousionC : 22
# cousionD : 24
# cousionE : NaN

In [ ]:
# imputation technique
# 1. Mean Imputation (avg)
# 2. Median Imputation (middle)
# 3. Mode Imputation (It will be replaced by most repetative no or String ) # for categorical data

In [84]:
df.head(5)

      Name   Age   Salary Dept
0      NaN  25.0   5000.0   HR
1     Amar   NaN   6000.0   IT
2    Rahul  30.0      NaN   HR
3   Vishal   NaN   7000.0   IT
4  Santosh  28.0  90000.0  NaN

In [85]:
df['Age'].mean()  # avg age of NaN values

np.float64(27.666666666666668)

In [75]:
df['Age'] = df['Age'].fillna(27.66)

In [104]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

df['Salary'] = df['Salary'].fillna(df['Salary'].median())

df['Dept'] = df['Dept'].fillna(df['Dept'].mode()[0])

df['Name'] = df['Name'].fillna("Guest/NA")

In [105]:
df.head(5)

       Name  Age   Salary Dept
0  Guest/NA   25   5000.0   HR
1      Amar   27   6000.0   IT
2     Rahul   30   6500.0   HR
3    Vishal   27   7000.0   IT
4   Santosh   28  90000.0   HR

In [87]:
# out layer : one number is extremely far from the other range  in salary it is far mean imputation wont work here

In [ ]:
# median imputation
# first it will do ascending then take the middle number 
#ex : 5 numbers are there it will take middle number 
# if 6 numbers are there it will do avetage  
#ex: 4+5/2  --> middle no

In [92]:
 df['Dept'].mode()  # here index is there so give index

0    HR
1    IT
Name: Dept, dtype: object

In [93]:
df['Dept'].mode()[0]

'HR'

In [100]:
df.dtypes

Name       object
Age       float64
Salary    float64
Dept       object
dtype: object

In [101]:
df['Age'] = df['Age'].astype(int)

In [102]:
df.head(10)

      Name  Age   Salary Dept
0      NaN   25   5000.0   HR
1     Amar   27   6000.0   IT
2    Rahul   30   6500.0   HR
3   Vishal   27   7000.0   IT
4  Santosh   28  90000.0   HR

In [103]:
df.dtypes

Name       object
Age         int64
Salary    float64
Dept       object
dtype: object

In [106]:
df['Age'] = df['Age'].fillna(df['Age'].mean())  # mean imputation
df['Age'] = df['Age'].astype(int)         # change the datatypes
df['Salary'] = df['Salary'].fillna(df['Salary'].median())   # median imputation
df['Dept'] = df['Dept'].fillna(df['Dept'].mode()[0])  # mode imputation
df['Name'] = df['Name'].fillna("Guest/NA") # default values

In [107]:
df.head(5)

       Name  Age   Salary Dept
0  Guest/NA   25   5000.0   HR
1      Amar   27   6000.0   IT
2     Rahul   30   6500.0   HR
3    Vishal   27   7000.0   IT
4   Santosh   28  90000.0   HR