In [127]:
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
from datetime import date

In [76]:
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\EmployeeDataToClean.csv" , encoding = "ISO-8859-1")

In [77]:
data.shape

(50, 14)

In [78]:
data.head(3)

,EmployeeID,NationalIDNumber,LoginID,Title,PhoneNumber,BirthDate,MaritalStatus,Gender,HireDate,Dept,Salary,Job Grade,CurrentFlag,rowguid
0,1,14417807,adventure-works\guy1,Gustavo Achong,9.257522e+09,21-02-1986 00:00,M,M,02-02-2013 00:00,Sales,2295.0,Admin,-1,{AAE1D04A-C237-4974-B4D5-935247737718}
1,2,253022876,adventure-works\kevin0,Catherine Abel,9.235868e+09,12-03-1991 00:00,S,M,31-08-2013 00:00,Sales,962.0,Management,-1,{1B480240-95C0-410F-A717-EB29943C8886}
2,3,509647174,NaN,Kim Abercrombie,9.416422e+09,21-09-1978 00:00,M,M,16-06-2014 00:00,Finance,4006.0,Admin,-1,{9BBBFB2C-EFBB-4217-9AB7-F97689328841}

In [79]:
list(data.columns)

['EmployeeID',
 'NationalIDNumber',
 'LoginID',
 'Title',
 'PhoneNumber',
 'BirthDate',
 'MaritalStatus',
 'Gender',
 'HireDate',
 'Dept',
 'Salary',
 'Job Grade',
 'CurrentFlag',
 'rowguid']

In [80]:
data.isna().sum()

EmployeeID           0
NationalIDNumber     0
LoginID             37
Title                0
PhoneNumber          7
BirthDate            0
MaritalStatus        0
Gender               0
HireDate             0
Dept                 0
Salary               6
Job Grade            0
CurrentFlag          0
rowguid              0
dtype: int64

In [81]:
(data.isna().sum() / data.shape[0]) * 100

EmployeeID           0.0
NationalIDNumber     0.0
LoginID             74.0
Title                0.0
PhoneNumber         14.0
BirthDate            0.0
MaritalStatus        0.0
Gender               0.0
HireDate             0.0
Dept                 0.0
Salary              12.0
Job Grade            0.0
CurrentFlag          0.0
rowguid              0.0
dtype: float64

In [ ]:
# if the column has more than 70 % we will drop the column

In [ ]:
# drop the column LoginID   -- Here we cannot impute the column
# in Phone number need to convert from 9.257522e+09 ( current data )
# 987561230 ---> Need to share 
# 987XXXX30 ---> Need to add masking

In [ ]:
# Data Cleaning Steps:
# 1)  drop the column LoginID  --> column has more than 70 % we will drop the column
# 2)  impute phone number (data Correction, also masking is needed)
# 3)  NationalIDNumber is not useful for reporting , unique records could be identified via emp_id, so this could be eleminated)
# 4) Drop the current flag (because you have only one unique value  -> useless)
# 5) rowguiid can give me unique empcount, since we have already employeecount (emp_id) we can discard this
# 6) Maritial status and Gender will create Falgs

In [82]:
data['CurrentFlag'].unique()

array([-1])

In [83]:
data['rowguid'].nunique()

50

In [84]:
data.dtypes

EmployeeID            int64
NationalIDNumber      int64
LoginID              object
Title                object
PhoneNumber         float64
BirthDate            object
MaritalStatus        object
Gender               object
HireDate             object
Dept                 object
Salary              float64
Job Grade            object
CurrentFlag           int64
rowguid              object
dtype: object

In [ ]:
# Datasteps implementation

In [85]:
data['PhoneNumber'] = data['PhoneNumber'].fillna(0000000000)

# data['PhoneNumber'] = data['PhoneNumber'].astype(int) # int casting error due to lot of NaN values are there 
# data type casting 
data['PhoneNumber'] = data['PhoneNumber'].astype("object")  # here decimal values will come to overcome this we use int64 thpe
data['PhoneNumber'] = data['PhoneNumber'].astype("int64")   # here warnings are coming to overcome this keep the import warnings syntax

In [86]:
data.head(5)

,EmployeeID,NationalIDNumber,LoginID,Title,PhoneNumber,BirthDate,MaritalStatus,Gender,HireDate,Dept,Salary,Job Grade,CurrentFlag,rowguid
0,1,14417807,adventure-works\guy1,Gustavo Achong,9257522351,21-02-1986 00:00,M,M,02-02-2013 00:00,Sales,2295.0,Admin,-1,{AAE1D04A-C237-4974-B4D5-935247737718}
1,2,253022876,adventure-works\kevin0,Catherine Abel,9235868360,12-03-1991 00:00,S,M,31-08-2013 00:00,Sales,962.0,Management,-1,{1B480240-95C0-410F-A717-EB29943C8886}
2,3,509647174,NaN,Kim Abercrombie,9416421559,21-09-1978 00:00,M,M,16-06-2014 00:00,Finance,4006.0,Admin,-1,{9BBBFB2C-EFBB-4217-9AB7-F97689328841}
3,4,112457891,NaN,Humberto Acevedo,8800042425,01-11-1978 00:00,S,M,10-07-2014 00:00,Logistics,4547.0,Admin,-1,{59747955-87B8-443F-8ED4-F8AD3AFDF3A9}
4,5,480168528,NaN,Pilar Ackerman,0,07-06-1963 00:00,M,M,16-07-2014 00:00,Human Resource,1932.0,Admin,-1,{1D955171-E773-4FAD-8382-40FD898D5D4D}

In [ ]:
# mask the phone number 9257522351 --> 925XXXXX51

In [40]:
a = "7075757415"

In [43]:
a[0:3]

'707'

In [41]:
a[-2:]

'15'

In [44]:
a[0:3] + "xxxx" + a[-2:]    # to create maskingin python

'707xxxx15'

In [87]:
def phn_masking(a):
    a = str(a)
    if a == '0':
        return "XXXXXXXXXX"
    else:
        result = a[0:3] + "XXXX" + a[-2:]
    return result

In [58]:
def f_materialstatus(a):
    if a == 'M':
        return 1
    else:
        return 0

In [88]:
data["Is_Married"] = data['MaritalStatus'].apply(f_materialstatus)
data["Is_Male"] = data['Gender'].apply(f_genderstatus)

In [89]:
def f_genderstatus(a):
    if a == 'M':
        return 1
    else:
        return 0

In [53]:
phn_masking(7075757415)

'707XXXX15'

In [54]:
phn_masking(0)

'XXXXXXXXXX'

In [90]:
data['PhoneNumber'] = data['PhoneNumber'].apply(phn_masking)

In [91]:
data.head(5)

,EmployeeID,NationalIDNumber,LoginID,Title,PhoneNumber,BirthDate,MaritalStatus,Gender,HireDate,Dept,Salary,Job Grade,CurrentFlag,rowguid,Is_Married,Is_Male
0,1,14417807,adventure-works\guy1,Gustavo Achong,925XXXX51,21-02-1986 00:00,M,M,02-02-2013 00:00,Sales,2295.0,Admin,-1,{AAE1D04A-C237-4974-B4D5-935247737718},1,1
1,2,253022876,adventure-works\kevin0,Catherine Abel,923XXXX60,12-03-1991 00:00,S,M,31-08-2013 00:00,Sales,962.0,Management,-1,{1B480240-95C0-410F-A717-EB29943C8886},0,1
2,3,509647174,NaN,Kim Abercrombie,941XXXX59,21-09-1978 00:00,M,M,16-06-2014 00:00,Finance,4006.0,Admin,-1,{9BBBFB2C-EFBB-4217-9AB7-F97689328841},1,1
3,4,112457891,NaN,Humberto Acevedo,880XXXX25,01-11-1978 00:00,S,M,10-07-2014 00:00,Logistics,4547.0,Admin,-1,{59747955-87B8-443F-8ED4-F8AD3AFDF3A9},0,1
4,5,480168528,NaN,Pilar Ackerman,XXXXXXXXXX,07-06-1963 00:00,M,M,16-07-2014 00:00,Human Resource,1932.0,Admin,-1,{1D955171-E773-4FAD-8382-40FD898D5D4D},1,1

In [92]:
data.columns

Index(['EmployeeID', 'NationalIDNumber', 'LoginID', 'Title', 'PhoneNumber',
       'BirthDate', 'MaritalStatus', 'Gender', 'HireDate', 'Dept', 'Salary',
       'Job Grade', 'CurrentFlag', 'rowguid', 'Is_Married', 'Is_Male'],
      dtype='object')

In [ ]:
# drop columns NationalIDNumber / LoginID / MaritalStatus / Gender / CurrentFlag / rowguid

In [93]:
data.shape

(50, 16)

In [94]:
data.drop("NationalIDNumber")  # will not work because we have to specify the axis

KeyError: "['NationalIDNumber'] not found in axis"

In [95]:
data = data.drop("NationalIDNumber" , axis = 1)

In [96]:
data.shape

(50, 15)

In [97]:
data = data.drop(["LoginID","MaritalStatus", "Gender", "CurrentFlag" , "rowguid"] , axis = 1)

In [ ]:
# Interview Question What is meant by axis = 1? 
# it is dropping the columns

In [98]:
data.shape

(50, 10)

In [99]:
data.head(5)

,EmployeeID,Title,PhoneNumber,BirthDate,HireDate,Dept,Salary,Job Grade,Is_Married,Is_Male
0,1,Gustavo Achong,925XXXX51,21-02-1986 00:00,02-02-2013 00:00,Sales,2295.0,Admin,1,1
1,2,Catherine Abel,923XXXX60,12-03-1991 00:00,31-08-2013 00:00,Sales,962.0,Management,0,1
2,3,Kim Abercrombie,941XXXX59,21-09-1978 00:00,16-06-2014 00:00,Finance,4006.0,Admin,1,1
3,4,Humberto Acevedo,880XXXX25,01-11-1978 00:00,10-07-2014 00:00,Logistics,4547.0,Admin,0,1
4,5,Pilar Ackerman,XXXXXXXXXX,07-06-1963 00:00,16-07-2014 00:00,Human Resource,1932.0,Admin,1,1

In [ ]:
# in python we dont have direct date datatype need to import time

In [100]:
data.dtypes

EmployeeID       int64
Title           object
PhoneNumber     object
BirthDate       object
HireDate        object
Dept            object
Salary         float64
Job Grade       object
Is_Married       int64
Is_Male          int64
dtype: object

In [29]:
b = "Python"

In [30]:
b[1]

'y'

In [31]:
b[5]

'n'

In [32]:
b[0:3]

'Pyt'

In [33]:
b[2:6]

'thon'

In [34]:
b[2:]

'thon'

In [35]:
c = "Data Engineering is Interesting Subject"

In [36]:
c[5:]

'Engineering is Interesting Subject'

In [ ]:
b = "Python"

In [38]:
b[-2:]

'on'

In [39]:
b[-4:]

'thon'

In [101]:
data.head(10)

,EmployeeID,Title,PhoneNumber,BirthDate,HireDate,Dept,Salary,Job Grade,Is_Married,Is_Male
0,1,Gustavo Achong,925XXXX51,21-02-1986 00:00,02-02-2013 00:00,Sales,2295.0,Admin,1,1
1,2,Catherine Abel,923XXXX60,12-03-1991 00:00,31-08-2013 00:00,Sales,962.0,Management,0,1
2,3,Kim Abercrombie,941XXXX59,21-09-1978 00:00,16-06-2014 00:00,Finance,4006.0,Admin,1,1
3,4,Humberto Acevedo,880XXXX25,01-11-1978 00:00,10-07-2014 00:00,Logistics,4547.0,Admin,0,1
4,5,Pilar Ackerman,XXXXXXXXXX,07-06-1963 00:00,16-07-2014 00:00,Human Resource,1932.0,Admin,1,1
5,6,Frances Adams,XXXXXXXXXX,26-01-1979 00:00,25-07-2014 00:00,Sales,NaN,Management,0,1
6,7,Margaret Smith,XXXXXXXXXX,25-11-1959 00:00,31-07-2014 00:00,sales,NaN,Operations,0,0
7,8,Carla Adams,XXXXXXXXXX,13-04-1960 00:00,11-08-2014 00:00,Finance,3989.0,Management,1,0
8,9,Jay Adams,918XXXX76,06-08-1956 00:00,11-08-2014 00:00,Finance,1636.0,Admin,1,0
9,10,Ronald Adina,941XXXX79,03-02-1960 00:00,12-08-2014 00:00,Logistics,3386.0,Admin,0,1

In [ ]:
# in salary null values are there

In [103]:
data["Salary"].unique()

array([2295.,  962., 4006., 4547., 1932.,   nan, 3989., 1636., 3386.,
       3676., 1128., 2301., 2887., 2154., 2741., 4096., 1998., 3408.,
       3390., 2034.,  600., 4406., 2042.,  664., 3723., 1161., 1711.,
       3199., 1513., 3978., 3639., 1134., 2298., 3843., 3880., 3967.,
        561., 1395.,  548., 1355., 1808., 2533., 3110., 4491., 2679.])

In [ ]:
list(data["Salary"].unique())

In [105]:
data["Salary"].max()

4547.0

In [106]:
data["Salary"].min()

548.0

In [107]:
data["Salary"] = data["Salary"].fillna(data["Salary"].mean())

In [108]:
data.head(10)

,EmployeeID,Title,PhoneNumber,BirthDate,HireDate,Dept,Salary,Job Grade,Is_Married,Is_Male
0,1,Gustavo Achong,925XXXX51,21-02-1986 00:00,02-02-2013 00:00,Sales,2295.000000,Admin,1,1
1,2,Catherine Abel,923XXXX60,12-03-1991 00:00,31-08-2013 00:00,Sales,962.000000,Management,0,1
2,3,Kim Abercrombie,941XXXX59,21-09-1978 00:00,16-06-2014 00:00,Finance,4006.000000,Admin,1,1
3,4,Humberto Acevedo,880XXXX25,01-11-1978 00:00,10-07-2014 00:00,Logistics,4547.000000,Admin,0,1
4,5,Pilar Ackerman,XXXXXXXXXX,07-06-1963 00:00,16-07-2014 00:00,Human Resource,1932.000000,Admin,1,1
5,6,Frances Adams,XXXXXXXXXX,26-01-1979 00:00,25-07-2014 00:00,Sales,2563.727273,Management,0,1
6,7,Margaret Smith,XXXXXXXXXX,25-11-1959 00:00,31-07-2014 00:00,sales,2563.727273,Operations,0,0
7,8,Carla Adams,XXXXXXXXXX,13-04-1960 00:00,11-08-2014 00:00,Finance,3989.000000,Management,1,0
8,9,Jay Adams,918XXXX76,06-08-1956 00:00,11-08-2014 00:00,Finance,1636.000000,Admin,1,0
9,10,Ronald Adina,941XXXX79,03-02-1960 00:00,12-08-2014 00:00,Logistics,3386.000000,Admin,0,1

In [111]:
# round the salary column
data["Salary"] = data["Salary"].round(3)

In [112]:
data.head(5)

,EmployeeID,Title,PhoneNumber,BirthDate,HireDate,Dept,Salary,Job Grade,Is_Married,Is_Male
0,1,Gustavo Achong,925XXXX51,21-02-1986 00:00,02-02-2013 00:00,Sales,2295.0,Admin,1,1
1,2,Catherine Abel,923XXXX60,12-03-1991 00:00,31-08-2013 00:00,Sales,962.0,Management,0,1
2,3,Kim Abercrombie,941XXXX59,21-09-1978 00:00,16-06-2014 00:00,Finance,4006.0,Admin,1,1
3,4,Humberto Acevedo,880XXXX25,01-11-1978 00:00,10-07-2014 00:00,Logistics,4547.0,Admin,0,1
4,5,Pilar Ackerman,XXXXXXXXXX,07-06-1963 00:00,16-07-2014 00:00,Human Resource,1932.0,Admin,1,1

In [120]:
data['Dept']  = data['Dept'].str.capitalize()

In [113]:
data.groupby("Dept")[["EmployeeID"]].count()

                EmployeeID
Dept
Finance                 11
Human Resource           6
Logistics                8
Production              14
Sales                    7
sales                    4

In [121]:
data.head(5)

,EmployeeID,Title,PhoneNumber,BirthDate,HireDate,Dept,Salary,Job Grade,Is_Married,Is_Male
0,1,Gustavo Achong,925XXXX51,21-02-1986 00:00,02-02-2013 00:00,Sales,2295.0,Admin,1,1
1,2,Catherine Abel,923XXXX60,12-03-1991 00:00,31-08-2013 00:00,Sales,962.0,Management,0,1
2,3,Kim Abercrombie,941XXXX59,21-09-1978 00:00,16-06-2014 00:00,Finance,4006.0,Admin,1,1
3,4,Humberto Acevedo,880XXXX25,01-11-1978 00:00,10-07-2014 00:00,Logistics,4547.0,Admin,0,1
4,5,Pilar Ackerman,XXXXXXXXXX,07-06-1963 00:00,16-07-2014 00:00,Human resource,1932.0,Admin,1,1

In [122]:
data.groupby("Dept")[["EmployeeID"]].count()

                EmployeeID
Dept
Finance                 11
Human resource           6
Logistics                8
Production              14
Sales                   11

In [114]:
a = "Santosh"

In [115]:
type(a)

str

In [116]:
a.capitalize()

'Santosh'

In [117]:
a.upper()

'SANTOSH'

In [118]:
a.lower()

'santosh'

In [123]:
data.dtypes

EmployeeID       int64
Title           object
PhoneNumber     object
BirthDate       object
HireDate        object
Dept            object
Salary         float64
Job Grade       object
Is_Married       int64
Is_Male          int64
dtype: object

In [139]:
data['BirthDate'] = pd.to_datetime(data['BirthDate'])

In [132]:
data.dtypes

EmployeeID              int64
Title                  object
PhoneNumber            object
BirthDate      datetime64[ns]
HireDate               object
Dept                   object
Salary                float64
Job Grade              object
Is_Married              int64
Is_Male                 int64
dtype: object

In [133]:
data.head(5)

,EmployeeID,Title,PhoneNumber,BirthDate,HireDate,Dept,Salary,Job Grade,Is_Married,Is_Male
0,1,Gustavo Achong,925XXXX51,1986-02-21,02-02-2013 00:00,Sales,2295.0,Admin,1,1
1,2,Catherine Abel,923XXXX60,1991-03-12,31-08-2013 00:00,Sales,962.0,Management,0,1
2,3,Kim Abercrombie,941XXXX59,1978-09-21,16-06-2014 00:00,Finance,4006.0,Admin,1,1
3,4,Humberto Acevedo,880XXXX25,1978-11-01,10-07-2014 00:00,Logistics,4547.0,Admin,0,1
4,5,Pilar Ackerman,XXXXXXXXXX,1963-06-07,16-07-2014 00:00,Human resource,1932.0,Admin,1,1

In [134]:
a = date.today()

In [135]:
a.year

2026

In [136]:
data['Age'] = a.year - data['BirthDate'].dt.year

In [137]:
data.head(5)

,EmployeeID,Title,PhoneNumber,BirthDate,HireDate,Dept,Salary,Job Grade,Is_Married,Is_Male,Age
0,1,Gustavo Achong,925XXXX51,1986-02-21,02-02-2013 00:00,Sales,2295.0,Admin,1,1,40
1,2,Catherine Abel,923XXXX60,1991-03-12,31-08-2013 00:00,Sales,962.0,Management,0,1,35
2,3,Kim Abercrombie,941XXXX59,1978-09-21,16-06-2014 00:00,Finance,4006.0,Admin,1,1,48
3,4,Humberto Acevedo,880XXXX25,1978-11-01,10-07-2014 00:00,Logistics,4547.0,Admin,0,1,48
4,5,Pilar Ackerman,XXXXXXXXXX,1963-06-07,16-07-2014 00:00,Human resource,1932.0,Admin,1,1,63

In [140]:
data['HireDate'] = pd.to_datetime(data['HireDate'])

ValueError: time data "31-08-2013 00:00" doesn't match format "%m-%d-%Y %H:%M", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [141]:
data.isna().sum()

EmployeeID     0
Title          0
PhoneNumber    0
BirthDate      0
HireDate       0
Dept           0
Salary         0
Job Grade      0
Is_Married     0
Is_Male        0
Age            0
dtype: int64