In [23]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\EmployeeDataToClean.csv" , encoding = "ISO-8859-1")

In [4]:
data.shape

(50, 14)

In [6]:
data.head(3)

,EmployeeID,NationalIDNumber,LoginID,Title,PhoneNumber,BirthDate,MaritalStatus,Gender,HireDate,Dept,Salary,Job Grade,CurrentFlag,rowguid
0,1,14417807,adventure-works\guy1,Gustavo Achong,9.257522e+09,21-02-1986 00:00,M,M,02-02-2013 00:00,Sales,2295.0,Admin,-1,{AAE1D04A-C237-4974-B4D5-935247737718}
1,2,253022876,adventure-works\kevin0,Catherine Abel,9.235868e+09,12-03-1991 00:00,S,M,31-08-2013 00:00,Sales,962.0,Management,-1,{1B480240-95C0-410F-A717-EB29943C8886}
2,3,509647174,NaN,Kim Abercrombie,9.416422e+09,21-09-1978 00:00,M,M,16-06-2014 00:00,Finance,4006.0,Admin,-1,{9BBBFB2C-EFBB-4217-9AB7-F97689328841}

In [10]:
list(data.columns)

['EmployeeID',
 'NationalIDNumber',
 'LoginID',
 'Title',
 'PhoneNumber',
 'BirthDate',
 'MaritalStatus',
 'Gender',
 'HireDate',
 'Dept',
 'Salary',
 'Job Grade',
 'CurrentFlag',
 'rowguid']

In [8]:
data.isna().sum()

EmployeeID           0
NationalIDNumber     0
LoginID             37
Title                0
PhoneNumber          7
BirthDate            0
MaritalStatus        0
Gender               0
HireDate             0
Dept                 0
Salary               6
Job Grade            0
CurrentFlag          0
rowguid              0
dtype: int64

In [9]:
(data.isna().sum() / data.shape[0]) * 100

EmployeeID           0.0
NationalIDNumber     0.0
LoginID             74.0
Title                0.0
PhoneNumber         14.0
BirthDate            0.0
MaritalStatus        0.0
Gender               0.0
HireDate             0.0
Dept                 0.0
Salary              12.0
Job Grade            0.0
CurrentFlag          0.0
rowguid              0.0
dtype: float64

In [ ]:
# if the column has more than 70 % we will drop the column

In [ ]:
# drop the column LoginID   -- Here we cannot impute the column
# in Phone number need to convert from 9.257522e+09 ( current data )
# 987561230 ---> Need to share 
# 987XXXX30 ---> Need to add masking

In [ ]:
# Data Cleaning Steps:
# 1)  drop the column LoginID  --  column has more than 70 % we will drop the column
# 2)  impute phone number (data Correction, also masking is needed)
# 3)  NationalIDNumber is not useful for reporting , unique records could be identified via emp_id, so this could be eleminated)
# 4) Drop the current flag (because you have only one unique value  -> useless)
# 5) rowguiid can give me unique empcount, since we have already employeecount (emp_id) we can discard this

In [11]:
data['CurrentFlag'].unique()

array([-1])

In [12]:
data['rowguid'].nunique()

50

In [13]:
data.dtypes

EmployeeID            int64
NationalIDNumber      int64
LoginID              object
Title                object
PhoneNumber         float64
BirthDate            object
MaritalStatus        object
Gender               object
HireDate             object
Dept                 object
Salary              float64
Job Grade            object
CurrentFlag           int64
rowguid              object
dtype: object

In [ ]:
# Datasteps implementation

In [24]:
data['PhoneNumber'] = data['PhoneNumber'].fillna(0000000000)

# data['PhoneNumber'] = data['PhoneNumber'].astype(int) # int casting error due to lot of NaN values are there 

data['PhoneNumber'] = data['PhoneNumber'].astype("object")  # here decimal values will come to overcome this we use int64 thpe
data['PhoneNumber'] = data['PhoneNumber'].astype("int64")   # here warnings are coming to overcome this keep the import warnings syntax

In [25]:
data.head(5)

,EmployeeID,NationalIDNumber,LoginID,Title,PhoneNumber,BirthDate,MaritalStatus,Gender,HireDate,Dept,Salary,Job Grade,CurrentFlag,rowguid
0,1,14417807,adventure-works\guy1,Gustavo Achong,9257522351,21-02-1986 00:00,M,M,02-02-2013 00:00,Sales,2295.0,Admin,-1,{AAE1D04A-C237-4974-B4D5-935247737718}
1,2,253022876,adventure-works\kevin0,Catherine Abel,9235868360,12-03-1991 00:00,S,M,31-08-2013 00:00,Sales,962.0,Management,-1,{1B480240-95C0-410F-A717-EB29943C8886}
2,3,509647174,NaN,Kim Abercrombie,9416421559,21-09-1978 00:00,M,M,16-06-2014 00:00,Finance,4006.0,Admin,-1,{9BBBFB2C-EFBB-4217-9AB7-F97689328841}
3,4,112457891,NaN,Humberto Acevedo,8800042425,01-11-1978 00:00,S,M,10-07-2014 00:00,Logistics,4547.0,Admin,-1,{59747955-87B8-443F-8ED4-F8AD3AFDF3A9}
4,5,480168528,NaN,Pilar Ackerman,0,07-06-1963 00:00,M,M,16-07-2014 00:00,Human Resource,1932.0,Admin,-1,{1D955171-E773-4FAD-8382-40FD898D5D4D}

In [ ]:
# mask the phone number 9257522351 --> 925XXXXX51

In [40]:
a = "7075757415"

In [43]:
a[0:3]

'707'

In [41]:
a[-2:]

'15'

In [44]:
a[0:3] + "xxxx" + a[-2:]    # to create maskingin python

'707xxxx15'

In [52]:
def phn_masking(a):
    a = str(a)
    if a == '0':
        return "XXXXXXXXXX"
    else:
        result = a[0:3] + "XXXX" + a[-2:]
    return result

In [58]:
def f_materialstatus(a):
    if a == 'M':
        return 1
    else:
        return 0

In [62]:
data["Is_Married"] = data['MaritalStatus'].apply(f_materialstatus)
data["Is_Male"] = data['Gender'].apply(f_genderstatus)

In [61]:
def f_genderstatus(a):
    if a == 'M':
        return 1
    else:
        return 0

In [53]:
phn_masking(7075757415)

'707XXXX15'

In [54]:
phn_masking(0)

'XXXXXXXXXX'

In [55]:
data['PhoneNumber'] = data['PhoneNumber'].apply(phn_masking)

In [63]:
data.head(5)

,EmployeeID,NationalIDNumber,LoginID,Title,PhoneNumber,BirthDate,MaritalStatus,Gender,HireDate,Dept,Salary,Job Grade,CurrentFlag,rowguid,Is_Married,Is_Male
0,1,14417807,adventure-works\guy1,Gustavo Achong,925XXXX51,21-02-1986 00:00,M,M,02-02-2013 00:00,Sales,2295.0,Admin,-1,{AAE1D04A-C237-4974-B4D5-935247737718},1,1
1,2,253022876,adventure-works\kevin0,Catherine Abel,923XXXX60,12-03-1991 00:00,S,M,31-08-2013 00:00,Sales,962.0,Management,-1,{1B480240-95C0-410F-A717-EB29943C8886},0,1
2,3,509647174,NaN,Kim Abercrombie,941XXXX59,21-09-1978 00:00,M,M,16-06-2014 00:00,Finance,4006.0,Admin,-1,{9BBBFB2C-EFBB-4217-9AB7-F97689328841},1,1
3,4,112457891,NaN,Humberto Acevedo,880XXXX25,01-11-1978 00:00,S,M,10-07-2014 00:00,Logistics,4547.0,Admin,-1,{59747955-87B8-443F-8ED4-F8AD3AFDF3A9},0,1
4,5,480168528,NaN,Pilar Ackerman,XXXXXXXXXX,07-06-1963 00:00,M,M,16-07-2014 00:00,Human Resource,1932.0,Admin,-1,{1D955171-E773-4FAD-8382-40FD898D5D4D},1,1

In [64]:
data.columns

Index(['EmployeeID', 'NationalIDNumber', 'LoginID', 'Title', 'PhoneNumber',
       'BirthDate', 'MaritalStatus', 'Gender', 'HireDate', 'Dept', 'Salary',
       'Job Grade', 'CurrentFlag', 'rowguid', 'Is_Married', 'Is_Male'],
      dtype='object')

In [ ]:
# drop columns NationalIDNumber / LoginID / MaritalStatus / Gender / CurrentFlag / rowguid

In [65]:
data.shape

(50, 16)

In [ ]:
data.drop("NationalIDNumber")  # will not work because we have to specify the axis

In [68]:
data = data.drop("NationalIDNumber" , axis = 1)

In [69]:
data.shape

(50, 15)

In [71]:
data = data.drop(["LoginID","MaritalStatus", "Gender", "CurrentFlag" , "rowguid"] , axis = 1)

In [72]:
data.shape

(50, 10)

In [73]:
data.head(5)

,EmployeeID,Title,PhoneNumber,BirthDate,HireDate,Dept,Salary,Job Grade,Is_Married,Is_Male
0,1,Gustavo Achong,925XXXX51,21-02-1986 00:00,02-02-2013 00:00,Sales,2295.0,Admin,1,1
1,2,Catherine Abel,923XXXX60,12-03-1991 00:00,31-08-2013 00:00,Sales,962.0,Management,0,1
2,3,Kim Abercrombie,941XXXX59,21-09-1978 00:00,16-06-2014 00:00,Finance,4006.0,Admin,1,1
3,4,Humberto Acevedo,880XXXX25,01-11-1978 00:00,10-07-2014 00:00,Logistics,4547.0,Admin,0,1
4,5,Pilar Ackerman,XXXXXXXXXX,07-06-1963 00:00,16-07-2014 00:00,Human Resource,1932.0,Admin,1,1

In [ ]:
# in python we dont have direct date datatype need to import time

In [74]:
data.dtypes

EmployeeID       int64
Title           object
PhoneNumber     object
BirthDate       object
HireDate        object
Dept            object
Salary         float64
Job Grade       object
Is_Married       int64
Is_Male          int64
dtype: object

In [29]:
b = "Python"

In [30]:
b[1]

'y'

In [31]:
b[5]

'n'

In [32]:
b[0:3]

'Pyt'

In [33]:
b[2:6]

'thon'

In [34]:
b[2:]

'thon'

In [35]:
c = "Data Engineering is Interesting Subject"

In [36]:
c[5:]

'Engineering is Interesting Subject'

In [ ]:
b = "Python"

In [38]:
b[-2:]

'on'

In [39]:
b[-4:]

'thon'