In [28]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [29]:
cust_data = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\Cust_Data.xlsx")

In [47]:
class cleaning_data:
    def __init__(self,data):
        self.data = data
    def volume_check(self):
        return self.data.shape
    def sample_data(self,N):
        return self.data.head(N)
    def row_count(self):
        print("The No of rows in given data set:" , cust_data.shape[0])
    def column_count(self):
        print("The No of Columns in given data set:" , cust_data.shape[1])
    def column_list(self):
        return list(cust_data.columns)
    def numerical_columns(self):
        return list(cust_data.select_dtypes(include = np.number).columns)
    def cartergial_columns(self):
        return list(cust_data.select_dtypes(exclude = np.number).columns)
    def drop_duplicates(self):
        self.data = self.data.drop_duplicates()
    def drop_nulls(self,column_name):
        self.data = self.data.dropna(subset = [column_name])
    def missing_value(self):
        return self.data.isna().sum()
    def missing_value_percentage(self):
        return (self.data.isna().sum() / self.data.shape[0]) * 100
    def impute_missing_val_with_mean(self,col_name):
        self.data['col_name'] = self.data['col_name'].fillna(self.data['col_name'].mean()).astype("int")
    def impute_missing_val_with_mode(self,col_name):
        self.data['col_name'] = self.data['col_name'].fillna(self.data['col_name'].mode()[0])
    def impute_missing_val_with_others(self,col_name):
        self.data['col_name'] = self.data['col_name'].fillna("Guest/Na")
    def phonenumber_masking(self, column_name):
        def mask_logic(b):
            b = str(b).split('.')[0] # to remove floating / decimal points any
            if b == '0' or b == '0000000000':
                return 'XXXXXXXXXX'
            else:
                returnb[0:3] + 'XXXXX' + b[-2:]
        self.data[column_name] = self.data[column_name].apply(mask_logic)

In [31]:
# we have 14 methods

In [32]:
d1 = cleaning_data(cust_data)

In [33]:
d1.volume_check()

(8, 4)

In [34]:
d1.sample_data(5)

   CustID  CustName   CustLoc  CustAge
0     1.0     Kiran      Pune     29.0
1     1.0     Kiran      Pune     29.0
2     2.0   Sathish  Maldives     30.0
3     3.0    Eshwar    Mumbai     34.0
4     5.0  Santhosh  Maldives     30.0

In [35]:
d1.row_count()

The No of rows in given data set: 8

In [36]:
d1.column_count()

The No of Columns in given data set: 4

In [37]:
d1.column_list()

['CustID', 'CustName', 'CustLoc', 'CustAge']

In [38]:
d1.numerical_columns()

['CustID', 'CustAge']

In [39]:
d1.cartergial_columns()

['CustName', 'CustLoc']

In [40]:
d1.drop_duplicates()

In [41]:
d1.drop_nulls('CustID')

In [42]:
d1.missing_value()

CustID      0
CustName    1
CustLoc     0
CustAge     1
dtype: int64

In [43]:
d1.missing_value_percentage()

CustID       0.000000
CustName    16.666667
CustLoc      0.000000
CustAge     16.666667
dtype: float64

In [44]:
d1.impute_missing_val_with_mean('CustAge')
d1.impute_missing_val_with_mode('CustLoc')
d1.impute_missing_val_with_others('CustName')

KeyError: 'col_name'

In [46]:
d1.sample_data(10)

   CustID  CustName    CustLoc  CustAge
0     1.0     Kiran       Pune     29.0
2     2.0   Sathish   Maldives     30.0
3     3.0    Eshwar     Mumbai     34.0
4     5.0  Santhosh   Maldives     30.0
5     6.0    Mahesh   Tirupati     32.0
7     7.0       NaN  Bangalore      NaN

In [ ]:
# phone no masking / drop columns
# write as method in class and do transformation using class

In [45]:
#data cleaning Methods
d1.drop_duplicates()
d1.drop_nulls('CustID')
d1.impute_missing_val_with_mean('CustAge')
d1.impute_missing_val_with_mode('CustLoc')
d1.impute_missing_val_with_others('CustName')
d1.phonenumber_masking("phone_no")
d1.drop_columns("row_guide")