In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Car_Data.csv") # to read complete data file

In [4]:
type(data)

pandas.core.frame.DataFrame

In [5]:
data.head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,2nd Owner

In [7]:
data.dtypes

Car_Name          object
Year               int64
Selling_Price    float64
Present_Price    float64
Kms_Driven         int64
Fuel_Type         object
Seller_Type       object
Transmission      object
Car_Owner         object
dtype: object

In [8]:
#1 Method (to get all petrol cars with all columns) (normal method)

In [10]:
data[data['Fuel_Type'] == 'Petrol'].head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,2nd Owner
10,alto 800,2017,2.85,3.60,2135,Petrol,Dealer,Manual,2nd Owner

In [11]:
# 1a) Method ( to get all petrol cars with selected columns) (normal method)

In [12]:
data[data['Fuel_Type'] == 'Petrol'] [['Car_Name', 'Year' , 'Fuel_Type']].head(5)

    Car_Name  Year Fuel_Type
0       ritz  2014    Petrol
2       ciaz  2017    Petrol
3    wagon r  2011    Petrol
6       ciaz  2015    Petrol
10  alto 800  2017    Petrol

In [13]:
#2 Method (to get all petrol cars with all columns) (dot method)

In [16]:
data[data['Fuel_Type'] == 'Petrol' ].head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,2nd Owner
10,alto 800,2017,2.85,3.60,2135,Petrol,Dealer,Manual,2nd Owner

In [15]:
data[data.Fuel_Type == 'Petrol' ].head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,2nd Owner
10,alto 800,2017,2.85,3.60,2135,Petrol,Dealer,Manual,2nd Owner

In [ ]:
#2 Method (to get all petrol cars ) (dot method with selected columns)

In [17]:
data[data.Fuel_Type == 'Petrol' ][['Car_Name' , 'Year' , 'Fuel_Type' ]].head(5)

    Car_Name  Year Fuel_Type
0       ritz  2014    Petrol
2       ciaz  2017    Petrol
3    wagon r  2011    Petrol
6       ciaz  2015    Petrol
10  alto 800  2017    Petrol

In [18]:
data[(data.Year == 2014) & (data.Fuel_Type == 'Petrol')].head(3) # not work because if column name had spaces

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
23,alto k10,2014,2.50,3.46,45280,Petrol,Dealer,Manual,1st Owner
41,alto k10,2014,2.55,3.98,46706,Petrol,Dealer,Manual,1st Owner

In [ ]:
#3) friendly methon sql (query Method)

In [22]:
data.query('Fuel_Type == "Petrol"').head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,2nd Owner
10,alto 800,2017,2.85,3.60,2135,Petrol,Dealer,Manual,2nd Owner

In [24]:
data.query('Year == 2014 and Fuel_Type == "Petrol"').head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
23,alto k10,2014,2.50,3.46,45280,Petrol,Dealer,Manual,1st Owner
41,alto k10,2014,2.55,3.98,46706,Petrol,Dealer,Manual,1st Owner
45,ciaz,2014,7.50,12.04,15000,Petrol,Dealer,Automatic,1st Owner
58,etios g,2014,4.10,6.80,39485,Petrol,Dealer,Manual,1st Owner

In [25]:
#3a) friendly methon sql (query Method  selected columns)

In [27]:
data.query('Year == 2014 and Fuel_Type == "Petrol"')[["Car_Name", "Year" ,"Fuel_Type"]].head(5)

    Car_Name  Year Fuel_Type
0       ritz  2014    Petrol
23  alto k10  2014    Petrol
41  alto k10  2014    Petrol
45      ciaz  2014    Petrol
58   etios g  2014    Petrol

In [29]:
#4) Lock and I lock method for all columns

In [30]:
data.loc[data['Fuel_Type'] == 'Petrol'].head(3)
data[data['Fuel_Type'] == 'Petrol'].head(3)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner

In [ ]:
#4) Lock and I lock method (selected columns)

In [31]:
data.loc[data['Fuel_Type'] == 'Petrol'][["Car_Name" , "Selling_Price"]].head(3)

  Car_Name  Selling_Price
0     ritz           3.35
2     ciaz           7.25
3  wagon r           2.85

In [32]:
# multiple conditions filter (all filters)

In [36]:
data[(data['Year'] == 2014) & (data["Fuel_Type"] == "Petrol")].head(5)

data[(data.Year == 2014) & (data.Fuel_Type == "Petrol")].head(5)

data.query('Year == 2014 and Fuel_Type == "Petrol"').head(5)

data.loc[(data['Year'] == 2014) & (data["Fuel_Type"] == "Petrol")].head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
23,alto k10,2014,2.50,3.46,45280,Petrol,Dealer,Manual,1st Owner
41,alto k10,2014,2.55,3.98,46706,Petrol,Dealer,Manual,1st Owner
45,ciaz,2014,7.50,12.04,15000,Petrol,Dealer,Automatic,1st Owner
58,etios g,2014,4.10,6.80,39485,Petrol,Dealer,Manual,1st Owner

In [41]:
# multiple conditions filter (all filters) (selected columns)
data[(data['Year'] == 2014) & (data["Fuel_Type"] == "Petrol")][["Car_Name" , "Year" ,"Fuel_Type"]].head(5)

data[(data.Year == 2014) & (data.Fuel_Type == "Petrol")][["Car_Name" , "Year" ,"Fuel_Type"]].head(5)

data.query('Year == 2014 and Fuel_Type == "Petrol"')[["Car_Name" , "Year" ,"Fuel_Type"]].head(5)

data.loc[(data['Year'] == 2014) & (data["Fuel_Type"] == "Petrol")][["Car_Name" , "Year" ,"Fuel_Type"]].head(5)

    Car_Name  Year Fuel_Type
0       ritz  2014    Petrol
23  alto k10  2014    Petrol
41  alto k10  2014    Petrol
45      ciaz  2014    Petrol
58   etios g  2014    Petrol