In [1]:
## What is joins 
## joins is the only possible way to get data from diff data frames

### Pandas Joins

In [38]:
# Joins
# Inner Join
# left Join
# Right Join 
# Full Join --(Outer Join)
# Self Join
# Cross Join ( cartesian Join)

In [3]:
# Interview Question in Joins SQL/ Pandas / Pyspark can Expect

#### Joins 
#### Commands which are used to combine columns from one or more dataframes
#### In general not all data will be present in data frame
#### For reporting purpose need complete information
#### data understandability

In [99]:
import pandas as pd

In [100]:
cust = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Custumer_Data.xlsx")

In [101]:
ord = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Orders_Data.csv")

In [102]:
cust.head(10)

   ID      Name  Age     Address  Wallet Bal
0   1    Ramesh   32  Ahmedabad          200
1   2    Khilan   23  Delhi             7500
2   3   kaushik   25  Kota             12000
3   4  Chaitali   22  Mumbai            6500
4   5    Hardik   27  Bhopal             600
5   6     Komal   26  MP                 750
6   7     Muffy   27  Indore             500

In [104]:
ord.head(5)   # NaN = Noat a Number

   OID        Date  C_ID  Amount
0  102  08-10-2009   3.0    3000
1  100  08-10-2009   3.0    1500
2  101  20-11-2009   2.0    1560
3  103  20-05-2008   4.0    2060
4  199  20-05-2008   NaN    1253

####  to join two data frames 
#### in sql ---   keyword is Join 
#### in pandas ---Keyword as Merge

In [19]:
# 1) to join two data frames with same column name  ( for all columns)

In [ ]:
# to combime more than one column in on condition
pd.merge(cust,ord, on = ["ID","Name"] ,how = "inner" ).head(5)                            # inner Join (all columns)

# by combining 2 columns 
pd.merge(cust,ord, left_on = ["ID","Name"],right_on = ["ID","Name"] , right_on = "ID" ,how = "inner" ).head(5)

In [ ]:
pd.merge(cust,ord, on = "ID" ,how = "inner" ).head(5)                          # inner Join (all columns)
pd.merge(cust,ord, left_on = "ID" , right_on = "ID" ,how = "inner" ).head(5)

In [ ]:
 # left Join (all columns) if common column name is same in both tables 

pd.merge(cust,ord, on = "ID" ,how = "left" ).head(10)

In [27]:
pd.merge(cust,ord, on = "ID" ,how = "right" ).head(10)               # right Join (all columns)if common column name is same in both tables

    ID      Name   Age     Address  Wallet Bal  OID        Date  Amount
0  3.0   kaushik  25.0  Kota           12000.0  102  08-10-2009    3000
1  3.0   kaushik  25.0  Kota           12000.0  100  08-10-2009    1500
2  2.0    Khilan  23.0  Delhi           7500.0  101  20-11-2009    1560
3  4.0  Chaitali  22.0  Mumbai          6500.0  103  20-05-2008    2060
4  NaN       NaN   NaN         NaN         NaN  199  20-05-2008    1253

In [29]:
# 2) to join two data frames with same column name  ( for selected columns)

In [34]:
pd.merge(cust, ord, on = "ID" ,how = "inner")[["Name","Address","OID","Amount"]].head(10)    #inner join
# or
pd.merge(cust, ord, left_on = "ID",right_on = "ID" ,how = "inner")[["Name","Address","OID","Amount"]].head(10)    #inner join

       Name     Address  OID  Amount
0    Khilan  Delhi       101    1560
1   kaushik  Kota        102    3000
2   kaushik  Kota        100    1500
3  Chaitali  Mumbai      103    2060

In [35]:
pd.merge(cust, ord, on = "ID" ,how = "left")[["Name","Address","OID","Amount"]].head(10)    #left join

       Name     Address    OID  Amount
0    Ramesh  Ahmedabad     NaN     NaN
1    Khilan  Delhi       101.0  1560.0
2   kaushik  Kota        102.0  3000.0
3   kaushik  Kota        100.0  1500.0
4  Chaitali  Mumbai      103.0  2060.0
5    Hardik  Bhopal        NaN     NaN
6     Komal  MP            NaN     NaN
7     Muffy  Indore        NaN     NaN

In [36]:
pd.merge(cust, ord, on = "ID" ,how = "right")[["Name","Address","OID","Amount"]].head(10)    #right join

       Name     Address  OID  Amount
0   kaushik  Kota        102    3000
1   kaushik  Kota        100    1500
2    Khilan  Delhi       101    1560
3  Chaitali  Mumbai      103    2060
4       NaN         NaN  199    1253

In [37]:
pd.merge(cust, ord, on = "ID" ,how = "outer")[["Name","Address","OID","Amount"]]    #full/outer join

       Name     Address    OID  Amount
0    Ramesh  Ahmedabad     NaN     NaN
1    Khilan  Delhi       101.0  1560.0
2   kaushik  Kota        102.0  3000.0
3   kaushik  Kota        100.0  1500.0
4  Chaitali  Mumbai      103.0  2060.0
5    Hardik  Bhopal        NaN     NaN
6     Komal  MP            NaN     NaN
7     Muffy  Indore        NaN     NaN
8       NaN         NaN  199.0  1253.0

In [60]:
# things to check
# 1) to join 2 dataframes with same column name (all columns)     {inner/left/right/outer}  --(Completed)
# 2) to join 2 dataframes with same column name (selcted columns) {inner/left/right/outer} --(Completed)
# 3)to join 2 dataframes with different column name (all columns) {inner/left/right/outer}--(Completed)
# 4)to join 2 dataframes with different column name (selected columns) {inner/left/right/outer}--(Completed)
# 5) to join 2 dataframe with different column name (all columns) and filtering records {inner/left/right/outer}--(Completed)
# 6) to join 2 dataframe with different column name (selected columns) and filtering records {inner/left/right/outer}--(Completed)
# 7) Add on (sorting / renaming/indexing/groupby etc)

In [42]:
ord = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Orders_Data.csv")

In [41]:
cust = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Custumer_Data.xlsx")

In [43]:
ord.head(5)

   OID        Date  C_ID  Amount
0  102  08-10-2009   3.0    3000
1  100  08-10-2009   3.0    1500
2  101  20-11-2009   2.0    1560
3  103  20-05-2008   4.0    2060
4  199  20-05-2008   NaN    1253

In [44]:
cust.head(10)

   ID      Name  Age     Address  Wallet Bal
0   1    Ramesh   32  Ahmedabad          200
1   2    Khilan   23  Delhi             7500
2   3   kaushik   25  Kota             12000
3   4  Chaitali   22  Mumbai            6500
4   5    Hardik   27  Bhopal             600
5   6     Komal   26  MP                 750
6   7     Muffy   27  Indore             500

In [47]:
#pd.merge(cust,ord, on = "ID" ,how = "inner" ).head(5)  ---> wont work

pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "inner" ).head(5)   # inner join

   ID      Name  Age     Address  Wallet Bal  OID        Date  C_ID  Amount
0   2    Khilan   23  Delhi             7500  101  20-11-2009   2.0    1560
1   3   kaushik   25  Kota             12000  102  08-10-2009   3.0    3000
2   3   kaushik   25  Kota             12000  100  08-10-2009   3.0    1500
3   4  Chaitali   22  Mumbai            6500  103  20-05-2008   4.0    2060

In [53]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "left" ).head(10)   # left join

   ID      Name  Age     Address  Wallet Bal    OID        Date  C_ID  Amount
0   1    Ramesh   32  Ahmedabad          200    NaN         NaN   NaN     NaN
1   2    Khilan   23  Delhi             7500  101.0  20-11-2009   2.0  1560.0
2   3   kaushik   25  Kota             12000  102.0  08-10-2009   3.0  3000.0
3   3   kaushik   25  Kota             12000  100.0  08-10-2009   3.0  1500.0
4   4  Chaitali   22  Mumbai            6500  103.0  20-05-2008   4.0  2060.0
5   5    Hardik   27  Bhopal             600    NaN         NaN   NaN     NaN
6   6     Komal   26  MP                 750    NaN         NaN   NaN     NaN
7   7     Muffy   27  Indore             500    NaN         NaN   NaN     NaN

In [52]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "right" ).head(10)   # right join

    ID      Name   Age     Address  Wallet Bal  OID        Date  C_ID  Amount
0  3.0   kaushik  25.0  Kota           12000.0  102  08-10-2009   3.0    3000
1  3.0   kaushik  25.0  Kota           12000.0  100  08-10-2009   3.0    1500
2  2.0    Khilan  23.0  Delhi           7500.0  101  20-11-2009   2.0    1560
3  4.0  Chaitali  22.0  Mumbai          6500.0  103  20-05-2008   4.0    2060
4  NaN       NaN   NaN         NaN         NaN  199  20-05-2008   NaN    1253

In [51]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "outer" ).head(10)   # full join

,ID,Name,Age,Address,Wallet Bal,OID,Date,C_ID,Amount
0,1.0,Ramesh,32.0,Ahmedabad,200.0,NaN,NaN,NaN,NaN
1,2.0,Khilan,23.0,Delhi,7500.0,101.0,20-11-2009,2.0,1560.0
2,3.0,kaushik,25.0,Kota,12000.0,102.0,08-10-2009,3.0,3000.0
3,3.0,kaushik,25.0,Kota,12000.0,100.0,08-10-2009,3.0,1500.0
4,4.0,Chaitali,22.0,Mumbai,6500.0,103.0,20-05-2008,4.0,2060.0
5,5.0,Hardik,27.0,Bhopal,600.0,NaN,NaN,NaN,NaN
6,6.0,Komal,26.0,MP,750.0,NaN,NaN,NaN,NaN
7,7.0,Muffy,27.0,Indore,500.0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,199.0,20-05-2008,NaN,1253.0

In [ ]:
# for selected columns

In [54]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "inner" )[["Name","Address","OID","Amount"]].head(5)   # inner join

       Name     Address  OID  Amount
0    Khilan  Delhi       101    1560
1   kaushik  Kota        102    3000
2   kaushik  Kota        100    1500
3  Chaitali  Mumbai      103    2060

In [55]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "left" )[["Name","Address","OID","Amount"]].head(10)   # left join

       Name     Address    OID  Amount
0    Ramesh  Ahmedabad     NaN     NaN
1    Khilan  Delhi       101.0  1560.0
2   kaushik  Kota        102.0  3000.0
3   kaushik  Kota        100.0  1500.0
4  Chaitali  Mumbai      103.0  2060.0

In [56]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "right" )[["Name","Address","OID","Amount"]].head(10)   # right join

       Name     Address  OID  Amount
0   kaushik  Kota        102    3000
1   kaushik  Kota        100    1500
2    Khilan  Delhi       101    1560
3  Chaitali  Mumbai      103    2060
4       NaN         NaN  199    1253

In [58]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "outer" )[["Name","Address","OID","Amount"]].head(10)   # full join

       Name     Address    OID  Amount
0    Ramesh  Ahmedabad     NaN     NaN
1    Khilan  Delhi       101.0  1560.0
2   kaushik  Kota        102.0  3000.0
3   kaushik  Kota        100.0  1500.0
4  Chaitali  Mumbai      103.0  2060.0
5    Hardik  Bhopal        NaN     NaN
6     Komal  MP            NaN     NaN
7     Muffy  Indore        NaN     NaN
8       NaN         NaN  199.0  1253.0

In [61]:
# 5) to join 2 dataframe with different column name (all columns) and filtering records {inner/left/right/outer}--(Completed)

In [62]:
result_df = pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "inner" )
# or)
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "inner" ).query("Name == 'kaushik'").head(10)

In [64]:
result_df.query("Name == 'kaushik'").head(10)

   ID     Name  Age     Address  Wallet Bal  OID        Date  C_ID  Amount
1   3  kaushik   25  Kota             12000  102  08-10-2009   3.0    3000
2   3  kaushik   25  Kota             12000  100  08-10-2009   3.0    1500

In [63]:
type(result_df)

pandas.core.frame.DataFrame

In [65]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "left" ).query("Name == 'kaushik'").head(10)

   ID     Name  Age     Address  Wallet Bal    OID        Date  C_ID  Amount
2   3  kaushik   25  Kota             12000  102.0  08-10-2009   3.0  3000.0
3   3  kaushik   25  Kota             12000  100.0  08-10-2009   3.0  1500.0

In [66]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "right" ).query("Name == 'kaushik'").head(10)

    ID     Name   Age     Address  Wallet Bal  OID        Date  C_ID  Amount
0  3.0  kaushik  25.0  Kota           12000.0  102  08-10-2009   3.0    3000
1  3.0  kaushik  25.0  Kota           12000.0  100  08-10-2009   3.0    1500

In [67]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "outer" ).query("Name == 'kaushik'").head(10)

    ID     Name   Age     Address  Wallet Bal    OID        Date  C_ID  Amount
2  3.0  kaushik  25.0  Kota           12000.0  102.0  08-10-2009   3.0  3000.0
3  3.0  kaushik  25.0  Kota           12000.0  100.0  08-10-2009   3.0  1500.0

In [68]:
# 6) to join 2 dataframe with different column name (selected columns) and filtering records {inner/left/right/outer}--(Completed)

In [69]:
# inner join
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "inner" )[["Name","Address","OID","Amount"]].query("Name == 'kaushik'").head(10)

      Name     Address  OID  Amount
1  kaushik  Kota        102    3000
2  kaushik  Kota        100    1500

In [70]:
# left join
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "left" )[["Name","Address","OID","Amount"]].query("Name == 'kaushik'").head(10)

      Name     Address    OID  Amount
2  kaushik  Kota        102.0  3000.0
3  kaushik  Kota        100.0  1500.0

In [71]:
# right join
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "right" )[["Name","Address","OID","Amount"]].query("Name == 'kaushik'").head(10)

      Name     Address  OID  Amount
0  kaushik  Kota        102    3000
1  kaushik  Kota        100    1500

In [72]:
# outer/full join
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "outer" )[["Name","Address","OID","Amount"]].query("Name == 'kaushik'").head(10)

      Name     Address    OID  Amount
2  kaushik  Kota        102.0  3000.0
3  kaushik  Kota        100.0  1500.0

In [73]:
# inner join 
# keeping the selected columns before the head 
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "inner" ).query("Name == 'kaushik'")[["Name","Address","OID","Amount"]].head(10)

      Name     Address  OID  Amount
1  kaushik  Kota        102    3000
2  kaushik  Kota        100    1500

In [76]:
# to find is null values
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "left" )[["Name","Address","OID","Amount"]].query("OID.isnull()").head(10)

     Name     Address  OID  Amount
0  Ramesh  Ahmedabad   NaN     NaN
5  Hardik  Bhopal      NaN     NaN
6   Komal  MP          NaN     NaN
7   Muffy  Indore      NaN     NaN

In [78]:
# to find not null 

pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "left" )[["Name","Address","OID","Amount"]].query("OID.notnull()").head(10)

       Name     Address    OID  Amount
1    Khilan  Delhi       101.0  1560.0
2   kaushik  Kota        102.0  3000.0
3   kaushik  Kota        100.0  1500.0
4  Chaitali  Mumbai      103.0  2060.0

### to join two data frames with same column names ( what if column names are same in 2 data frames)

In [2]:
cust2 = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Custumer_Data.xlsx")

In [3]:
ord1 = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Orders_Data1.xlsx"  )

In [4]:
cust2.head(3)

   ID     Name  Age     Address  Wallet Bal
0   1   Ramesh   32  Ahmedabad          200
1   2   Khilan   23  Delhi             7500
2   3  kaushik   25  Kota             12000

In [5]:
ord1.head(3)

   OID       Date     Name  C_ID  Amount
0  102 2009-10-08  kaushik   3.0    3000
1  100 2009-10-08  kaushik   3.0    1500
2  101 2009-11-20   Khilan   2.0    1560

In [13]:
# same column name is having the different names in out put it is built in function in python

pd.merge(cust2 , ord1 , left_on = "ID" , right_on = "C_ID" , how = "inner").head(5)

,ID,Name_x,Age,Address,Wallet Bal,OID,Date,Name_y,C_ID,Amount
0,2,Khilan,23,Delhi,7500,101,2009-11-20,Khilan,2.0,1560
1,3,kaushik,25,Kota,12000,102,2009-10-08,kaushik,3.0,3000
2,3,kaushik,25,Kota,12000,100,2009-10-08,kaushik,3.0,1500
3,4,Chaitali,22,Mumbai,6500,103,2008-05-20,Chaitali,4.0,2060

In [ ]:
# here same column - name is available in both tables it is not working 

pd.merge(cust2 , ord1 , left_on = "ID" , right_on = "C_ID" , how = "inner")[["ID", "Name" , "Date" ,"OID"]].head(5)

In [12]:
pd.merge(cust2 , ord1 , left_on = "ID" , right_on = "C_ID" , how = "inner")[["ID", "Name_x" , "Date" ,"OID"]].head(5)

   ID    Name_x       Date  OID
0   2    Khilan 2009-11-20  101
1   3   kaushik 2009-10-08  102
2   3   kaushik 2009-10-08  100
3   4  Chaitali 2008-05-20  103

In [ ]:
# want to change own suffix name in this above code

In [17]:
pd.merge(cust2 , ord1 , left_on = "ID" , right_on = "C_ID" , how = "inner", suffixes=('_cust','_ord')).head(5)
# we can give any name for suffixes -- default function by python

,ID,Name_cust,Age,Address,Wallet Bal,OID,Date,Name_ord,C_ID,Amount
0,2,Khilan,23,Delhi,7500,101,2009-11-20,Khilan,2.0,1560
1,3,kaushik,25,Kota,12000,102,2009-10-08,kaushik,3.0,3000
2,3,kaushik,25,Kota,12000,100,2009-10-08,kaushik,3.0,1500
3,4,Chaitali,22,Mumbai,6500,103,2008-05-20,Chaitali,4.0,2060

In [19]:
pd.merge(cust2 , ord1 , left_on = "ID" , right_on = "C_ID" , how = "inner", suffixes=('cust','ord')).head(5) # not readable

,ID,Namecust,Age,Address,Wallet Bal,OID,Date,Nameord,C_ID,Amount
0,2,Khilan,23,Delhi,7500,101,2009-11-20,Khilan,2.0,1560
1,3,kaushik,25,Kota,12000,102,2009-10-08,kaushik,3.0,3000
2,3,kaushik,25,Kota,12000,100,2009-10-08,kaushik,3.0,1500
3,4,Chaitali,22,Mumbai,6500,103,2008-05-20,Chaitali,4.0,2060

In [26]:
# to rename the customer name 
pd.merge(cust2 , ord1 , left_on = "ID" , right_on = "C_ID" , how = "inner", suffixes=('cust','ord')) \
    .rename(columns = {"Namecust": "Customer_Name", "Nameord": "Order_Name"})

,ID,Customer_Name,Age,Address,Wallet Bal,OID,Date,Order_Name,C_ID,Amount
0,2,Khilan,23,Delhi,7500,101,2009-11-20,Khilan,2.0,1560
1,3,kaushik,25,Kota,12000,102,2009-10-08,kaushik,3.0,3000
2,3,kaushik,25,Kota,12000,100,2009-10-08,kaushik,3.0,1500
3,4,Chaitali,22,Mumbai,6500,103,2008-05-20,Chaitali,4.0,2060

In [27]:
pd.merge(cust2 , ord1 , left_on = "ID" , right_on = "C_ID" , how = "inner", suffixes=('cust','ord'),sort = True) \
    .rename(columns = {"Namecust": "Customer_Name", "Nameord": "Order_Name"})

,ID,Customer_Name,Age,Address,Wallet Bal,OID,Date,Order_Name,C_ID,Amount
0,2,Khilan,23,Delhi,7500,101,2009-11-20,Khilan,2.0,1560
1,3,kaushik,25,Kota,12000,102,2009-10-08,kaushik,3.0,3000
2,3,kaushik,25,Kota,12000,100,2009-10-08,kaushik,3.0,1500
3,4,Chaitali,22,Mumbai,6500,103,2008-05-20,Chaitali,4.0,2060

In [35]:
ord1 = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Orders_Data.csv")

In [28]:
cust2 = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Custumer_Data.xlsx")

In [36]:
ord1.head(3)

   OID        Date  C_ID  Amount
0  102  08-10-2009   3.0    3000
1  100  08-10-2009   3.0    1500
2  101  20-11-2009   2.0    1560

In [31]:
cust2.head(5)

   ID      Name  Age     Address  Wallet Bal
0   1    Ramesh   32  Ahmedabad          200
1   2    Khilan   23  Delhi             7500
2   3   kaushik   25  Kota             12000
3   4  Chaitali   22  Mumbai            6500
4   5    Hardik   27  Bhopal             600

In [38]:
#pd.merge(cust2,ord1, left_on = "ID" ,right_on = "C_ID").head(5)  # by default it takes inner join
pd.merge(cust2,ord1, left_on = "ID" ,right_on = "C_ID" , how = "inner")[["Name" , "OID" , "ID" , "Date" ]].head(5)

       Name  OID  ID        Date
0    Khilan  101   2  20-11-2009
1   kaushik  102   3  08-10-2009
2   kaushik  100   3  08-10-2009
3  Chaitali  103   4  20-05-2008

In [40]:
pd.merge(cust2,ord1, left_on = "ID" ,right_on = "C_ID" , how = "inner" , sort = False)[["Name" , "OID" , "ID" , "Date" ]].head(5)

       Name  OID  ID        Date
0    Khilan  101   2  20-11-2009
1   kaushik  102   3  08-10-2009
2   kaushik  100   3  08-10-2009
3  Chaitali  103   4  20-05-2008

In [39]:
pd.merge(cust2,ord1, left_on = "ID" ,right_on = "C_ID" , how = "inner" , sort = True)[["Name" , "OID" , "ID" , "Date" ]].head(5)

       Name  OID  ID        Date
0    Khilan  101   2  20-11-2009
1   kaushik  102   3  08-10-2009
2   kaushik  100   3  08-10-2009
3  Chaitali  103   4  20-05-2008

In [ ]:
ord1 = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Orders_Data.csv")

In [41]:
cust3 = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Cust1_230426.xlsx")

In [42]:
ord1.head(3)

   OID        Date  C_ID  Amount
0  102  08-10-2009   3.0    3000
1  100  08-10-2009   3.0    1500
2  101  20-11-2009   2.0    1560

In [43]:
cust3.head(5)

   ID      Name  Age     Address  Wallet Bal
0   5    Hardik   27  Bhopal             600
1   7     Muffy   27  Indore             500
2   1    Ramesh   32  Ahmedabad          200
3   4  Chaitali   22  Mumbai            6500
4   6     Komal   26  MP                 750

In [54]:
pd.merge(cust3,ord1, left_on = "ID" ,right_on = "C_ID" , how = "left" , sort = False)[["ID" , "Name" , "OID" , "Date" ]].head(10)

   ID      Name    OID        Date
0   5    Hardik    NaN         NaN
1   7     Muffy    NaN         NaN
2   1    Ramesh    NaN         NaN
3   4  Chaitali  103.0  20-05-2008
4   6     Komal    NaN         NaN
5   3   kaushik  102.0  08-10-2009
6   3   kaushik  100.0  08-10-2009
7   2    Khilan  101.0  20-11-2009

In [52]:
pd.merge(cust3,ord1, left_on = "ID" ,right_on = "C_ID" , how = "left" , sort = True)[["ID" ,"Name" , "OID" ,  "Date" ]].head(10)

   ID      Name    OID        Date
0   1    Ramesh    NaN         NaN
1   2    Khilan  101.0  20-11-2009
2   3   kaushik  102.0  08-10-2009
3   3   kaushik  100.0  08-10-2009
4   4  Chaitali  103.0  20-05-2008
5   5    Hardik    NaN         NaN
6   6     Komal    NaN         NaN
7   7     Muffy    NaN         NaN

In [71]:
# cross Join  ( cartesian join)
# will give helpful to get combination if there is no common column

In [68]:
dict1 = {"Colour":["white","Black" , "Gold" ,"blue"]}
dict2 = {"Size":["S", "L" ,"M" ,"XL" ,"XXL" ]}

In [62]:
type(dict1)

dict

In [63]:
print(dict1)

{'Colour': ['white', 'Black', 'Gold', 'blue']}

In [58]:
df1 = pd.DataFrame({"Colour":["white","Black" , "Gold" ,"blue"]})

In [59]:
type(df1)

pandas.core.frame.DataFrame

In [60]:
df1.head(5)

  Colour
0  white
1  Black
2   Gold
3   blue

In [65]:
# how do you convert the dictonary into a dataframe 
# in python we had a inbuilt function called pd.DataFrame 
# in DataFrame if you pass a dict auttomatically convert into a table format

In [66]:
df2 = pd.DataFrame(dict1)

In [67]:
df2.head(5)

  Colour
0  white
1  Black
2   Gold
3   blue

In [69]:
df3 = pd.DataFrame(dict2)

In [70]:
df3.head(5)

  Size
0    S
1    L
2    M
3   XL
4  XXL

In [72]:
pd.merge(df2,df3, how = "cross")

   Colour Size
0   white    S
1   white    L
2   white    M
3   white   XL
4   white  XXL
5   Black    S
6   Black    L
7   Black    M
8   Black   XL
9   Black  XXL
10   Gold    S
11   Gold    L
12   Gold    M
13   Gold   XL
14   Gold  XXL
15   blue    S
16   blue    L
17   blue    M
18   blue   XL
19   blue  XXL

In [74]:
# Self Join 
# table joining with same table (only one table)

In [75]:
emp = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Emp1.csv" , encoding = "ISO-8859-1")

In [81]:
training = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Training1.csv" , encoding = "ISO-8859-1")

In [76]:
emp.head(5)

,EmployeeID,ManagerID,Title,MaritalStatus,Gender,HireDate,Dept,JobGrade
0,1,16,Gustavo Achong,M,M,02-02-2013 00:00,Sales,Admin
1,2,6,Catherine Abel,S,M,31-08-2013 00:00,Sales,Management
2,3,12,Kim Abercrombie,M,M,16-06-2014 00:00,Finance,Admin
3,4,3,Humberto Acevedo,S,M,10-07-2014 00:00,Logistics,Admin
4,5,263,Pilar Ackerman,M,M,16-07-2014 00:00,Human Resource,Admin

In [84]:
emp1= emp[["EmployeeID" , "ManagerID" ,"Title"]]

In [85]:
emp1.head(5)

   EmployeeID  ManagerID             Title
0           1         16    Gustavo Achong
1           2          6    Catherine Abel
2           3         12   Kim Abercrombie
3           4          3  Humberto Acevedo
4           5        263    Pilar Ackerman

In [88]:
pd.merge(emp1,emp1 , left_on  = "ManagerID" , right_on  = "EmployeeID" , how = "left") .head(5)

# why _x & _y is coming bcoz same column names in both tables

,EmployeeID_x,ManagerID_x,Title_x,EmployeeID_y,ManagerID_y,Title_y
0,1,16,Gustavo Achong,16.0,21.0,Lili Alameda
1,2,6,Catherine Abel,6.0,109.0,Frances Adams
2,3,12,Kim Abercrombie,12.0,109.0,James Aguilar
3,4,3,Humberto Acevedo,3.0,12.0,Kim Abercrombie
4,5,263,Pilar Ackerman,NaN,NaN,NaN

In [93]:
pd.merge(emp1,emp1 , left_on  = "ManagerID" , right_on  = "EmployeeID" , how = "left")[["Title_x" , "Title_y"]] \
    .rename(columns = {"Title_x":"Employee_Name" , "Title_y":"Manager_Name" } )\
    .head(10)

      Employee_Name      Manager_Name
0    Gustavo Achong      Lili Alameda
1    Catherine Abel     Frances Adams
2   Kim Abercrombie     James Aguilar
3  Humberto Acevedo   Kim Abercrombie
4    Pilar Ackerman               NaN
5     Frances Adams               NaN
6    Margaret Smith  Gregory Alderson
7       Carla Adams               NaN
8         Jay Adams   Kim Abercrombie
9      Ronald Adina               NaN

In [95]:
pd.merge(emp1,emp1 , left_on  = "ManagerID" , right_on  = "EmployeeID" , how = "inner")[["Title_x" , "Title_y"]] \
    .rename(columns = {"Title_x":"Employee_Name" , "Title_y":"Manager_Name" } )\
    .head(10)
# here null values vill not come

      Employee_Name      Manager_Name
0    Gustavo Achong      Lili Alameda
1    Catherine Abel     Frances Adams
2   Kim Abercrombie     James Aguilar
3  Humberto Acevedo   Kim Abercrombie
4    Margaret Smith  Gregory Alderson
5         Jay Adams   Kim Abercrombie
6   Samuel Agcaoili   Kim Abercrombie
7  François Ferrier  Gregory Alderson
8      Lili Alameda  Gregory Alderson
9     Anna Albright  Gregory Alderson

In [96]:
# how to join more than two tables