In [1]:
## What is joins 
## joins is the only possible way to get data from diff data frames

In [38]:
# Joins
# Inner Join
# left Join
# Right Join 
# Full Join --(Outer Join)
# Self Join
# Cross Join ( cartesian Join)

In [3]:
# Interview Question in Joins SQL/ Pandas / Pyspark can Expect

In [4]:
# Joins 
# Commands which are used to combine columns from one or more dataframes
# In general not all data will be present in data frame
# For reporting purpose need complete information
# data understandability

In [5]:
import pandas as pd

In [13]:
cust = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Custumer_Data.xlsx")

In [9]:
ord = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Orders_Data.csv")

In [15]:
cust.head(10)

   ID      Name  Age     Address  Wallet Bal
0   1    Ramesh   32  Ahmedabad          200
1   2    Khilan   23  Delhi             7500
2   3   kaushik   25  Kota             12000
3   4  Chaitali   22  Mumbai            6500
4   5    Hardik   27  Bhopal             600
5   6     Komal   26  MP                 750
6   7     Muffy   27  Indore             500

In [28]:
ord.head(5)   # NaN = Noat a Number

   OID        Date   ID  Amount
0  102  08-10-2009  3.0    3000
1  100  08-10-2009  3.0    1500
2  101  20-11-2009  2.0    1560
3  103  20-05-2008  4.0    2060
4  199  20-05-2008  NaN    1253

In [17]:
#  to join two data frames 
# in sql ---   keyword is Join 
# in pandas ---Keyword as Merge

In [19]:
# 1) to join two data frames with same column name  ( for all columns)

In [ ]:
# to combime more than one column in on condition
pd.merge(cust,ord, on = ["ID","Name"] ,how = "inner" ).head(5)   # inner Join (all columns)
pd.merge(cust,ord, left_on = ["ID","Name"],right_on = ["ID","Name"] , right_on = "ID" ,how = "inner" ).head(5)

In [ ]:
pd.merge(cust,ord, on = "ID" ,how = "inner" ).head(5)   # inner Join (all columns)
pd.merge(cust,ord, left_on = "ID" , right_on = "ID" ,how = "inner" ).head(5)

In [26]:
pd.merge(cust,ord, on = "ID" ,how = "left" ).head(10)   # left Join (all columns)

   ID      Name  Age     Address  Wallet Bal    OID        Date  Amount
0   1    Ramesh   32  Ahmedabad          200    NaN         NaN     NaN
1   2    Khilan   23  Delhi             7500  101.0  20-11-2009  1560.0
2   3   kaushik   25  Kota             12000  102.0  08-10-2009  3000.0
3   3   kaushik   25  Kota             12000  100.0  08-10-2009  1500.0
4   4  Chaitali   22  Mumbai            6500  103.0  20-05-2008  2060.0
5   5    Hardik   27  Bhopal             600    NaN         NaN     NaN
6   6     Komal   26  MP                 750    NaN         NaN     NaN
7   7     Muffy   27  Indore             500    NaN         NaN     NaN

In [27]:
pd.merge(cust,ord, on = "ID" ,how = "right" ).head(10)   # right Join (all columns)

    ID      Name   Age     Address  Wallet Bal  OID        Date  Amount
0  3.0   kaushik  25.0  Kota           12000.0  102  08-10-2009    3000
1  3.0   kaushik  25.0  Kota           12000.0  100  08-10-2009    1500
2  2.0    Khilan  23.0  Delhi           7500.0  101  20-11-2009    1560
3  4.0  Chaitali  22.0  Mumbai          6500.0  103  20-05-2008    2060
4  NaN       NaN   NaN         NaN         NaN  199  20-05-2008    1253

In [29]:
# 2) to join two data frames with same column name  ( for selected columns)

In [34]:
pd.merge(cust, ord, on = "ID" ,how = "inner")[["Name","Address","OID","Amount"]].head(10)    #inner join
pd.merge(cust, ord, left_on = "ID",right_on = "ID" ,how = "inner")[["Name","Address","OID","Amount"]].head(10)    #inner join

       Name     Address  OID  Amount
0    Khilan  Delhi       101    1560
1   kaushik  Kota        102    3000
2   kaushik  Kota        100    1500
3  Chaitali  Mumbai      103    2060

In [35]:
pd.merge(cust, ord, on = "ID" ,how = "left")[["Name","Address","OID","Amount"]].head(10)    #left join

       Name     Address    OID  Amount
0    Ramesh  Ahmedabad     NaN     NaN
1    Khilan  Delhi       101.0  1560.0
2   kaushik  Kota        102.0  3000.0
3   kaushik  Kota        100.0  1500.0
4  Chaitali  Mumbai      103.0  2060.0
5    Hardik  Bhopal        NaN     NaN
6     Komal  MP            NaN     NaN
7     Muffy  Indore        NaN     NaN

In [36]:
pd.merge(cust, ord, on = "ID" ,how = "right")[["Name","Address","OID","Amount"]].head(10)    #right join

       Name     Address  OID  Amount
0   kaushik  Kota        102    3000
1   kaushik  Kota        100    1500
2    Khilan  Delhi       101    1560
3  Chaitali  Mumbai      103    2060
4       NaN         NaN  199    1253

In [37]:
pd.merge(cust, ord, on = "ID" ,how = "outer")[["Name","Address","OID","Amount"]]    #full/outer join

       Name     Address    OID  Amount
0    Ramesh  Ahmedabad     NaN     NaN
1    Khilan  Delhi       101.0  1560.0
2   kaushik  Kota        102.0  3000.0
3   kaushik  Kota        100.0  1500.0
4  Chaitali  Mumbai      103.0  2060.0
5    Hardik  Bhopal        NaN     NaN
6     Komal  MP            NaN     NaN
7     Muffy  Indore        NaN     NaN
8       NaN         NaN  199.0  1253.0

In [60]:
# things to check
# 1) to join 2 dataframes with same column name (all columns)     {inner/left/right/outer}  --(Completed)
# 2) to join 2 dataframes with same column name (selcted columns) {inner/left/right/outer} --(Completed)
# 3)to join 2 dataframes with different column name (all columns) {inner/left/right/outer}--(Completed)
# 4)to join 2 dataframes with different column name (selected columns) {inner/left/right/outer}--(Completed)
# 5) to join 2 dataframe with different column name (all columns) and filtering records {inner/left/right/outer}--(Completed)
# 6) to join 2 dataframe with different column name (selected columns) and filtering records {inner/left/right/outer}--(Completed)
# 7) Add on (sorting / renaming/indexing/groupby etc)

In [42]:
ord = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Orders_Data.csv")

In [41]:
cust = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Custumer_Data.xlsx")

In [43]:
ord.head(5)

   OID        Date  C_ID  Amount
0  102  08-10-2009   3.0    3000
1  100  08-10-2009   3.0    1500
2  101  20-11-2009   2.0    1560
3  103  20-05-2008   4.0    2060
4  199  20-05-2008   NaN    1253

In [44]:
cust.head(10)

   ID      Name  Age     Address  Wallet Bal
0   1    Ramesh   32  Ahmedabad          200
1   2    Khilan   23  Delhi             7500
2   3   kaushik   25  Kota             12000
3   4  Chaitali   22  Mumbai            6500
4   5    Hardik   27  Bhopal             600
5   6     Komal   26  MP                 750
6   7     Muffy   27  Indore             500

In [47]:
#pd.merge(cust,ord, on = "ID" ,how = "inner" ).head(5)  ---> wont work

pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "inner" ).head(5)   # inner join

   ID      Name  Age     Address  Wallet Bal  OID        Date  C_ID  Amount
0   2    Khilan   23  Delhi             7500  101  20-11-2009   2.0    1560
1   3   kaushik   25  Kota             12000  102  08-10-2009   3.0    3000
2   3   kaushik   25  Kota             12000  100  08-10-2009   3.0    1500
3   4  Chaitali   22  Mumbai            6500  103  20-05-2008   4.0    2060

In [53]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "left" ).head(10)   # left join

   ID      Name  Age     Address  Wallet Bal    OID        Date  C_ID  Amount
0   1    Ramesh   32  Ahmedabad          200    NaN         NaN   NaN     NaN
1   2    Khilan   23  Delhi             7500  101.0  20-11-2009   2.0  1560.0
2   3   kaushik   25  Kota             12000  102.0  08-10-2009   3.0  3000.0
3   3   kaushik   25  Kota             12000  100.0  08-10-2009   3.0  1500.0
4   4  Chaitali   22  Mumbai            6500  103.0  20-05-2008   4.0  2060.0
5   5    Hardik   27  Bhopal             600    NaN         NaN   NaN     NaN
6   6     Komal   26  MP                 750    NaN         NaN   NaN     NaN
7   7     Muffy   27  Indore             500    NaN         NaN   NaN     NaN

In [52]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "right" ).head(10)   # right join

    ID      Name   Age     Address  Wallet Bal  OID        Date  C_ID  Amount
0  3.0   kaushik  25.0  Kota           12000.0  102  08-10-2009   3.0    3000
1  3.0   kaushik  25.0  Kota           12000.0  100  08-10-2009   3.0    1500
2  2.0    Khilan  23.0  Delhi           7500.0  101  20-11-2009   2.0    1560
3  4.0  Chaitali  22.0  Mumbai          6500.0  103  20-05-2008   4.0    2060
4  NaN       NaN   NaN         NaN         NaN  199  20-05-2008   NaN    1253

In [51]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "outer" ).head(10)   # full join

,ID,Name,Age,Address,Wallet Bal,OID,Date,C_ID,Amount
0,1.0,Ramesh,32.0,Ahmedabad,200.0,NaN,NaN,NaN,NaN
1,2.0,Khilan,23.0,Delhi,7500.0,101.0,20-11-2009,2.0,1560.0
2,3.0,kaushik,25.0,Kota,12000.0,102.0,08-10-2009,3.0,3000.0
3,3.0,kaushik,25.0,Kota,12000.0,100.0,08-10-2009,3.0,1500.0
4,4.0,Chaitali,22.0,Mumbai,6500.0,103.0,20-05-2008,4.0,2060.0
5,5.0,Hardik,27.0,Bhopal,600.0,NaN,NaN,NaN,NaN
6,6.0,Komal,26.0,MP,750.0,NaN,NaN,NaN,NaN
7,7.0,Muffy,27.0,Indore,500.0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,199.0,20-05-2008,NaN,1253.0

In [ ]:
# for selected columns

In [54]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "inner" )[["Name","Address","OID","Amount"]].head(5)   # inner join

       Name     Address  OID  Amount
0    Khilan  Delhi       101    1560
1   kaushik  Kota        102    3000
2   kaushik  Kota        100    1500
3  Chaitali  Mumbai      103    2060

In [55]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "left" )[["Name","Address","OID","Amount"]].head(10)   # left join

       Name     Address    OID  Amount
0    Ramesh  Ahmedabad     NaN     NaN
1    Khilan  Delhi       101.0  1560.0
2   kaushik  Kota        102.0  3000.0
3   kaushik  Kota        100.0  1500.0
4  Chaitali  Mumbai      103.0  2060.0

In [56]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "right" )[["Name","Address","OID","Amount"]].head(10)   # right join

       Name     Address  OID  Amount
0   kaushik  Kota        102    3000
1   kaushik  Kota        100    1500
2    Khilan  Delhi       101    1560
3  Chaitali  Mumbai      103    2060
4       NaN         NaN  199    1253

In [58]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "outer" )[["Name","Address","OID","Amount"]].head(10)   # full join

       Name     Address    OID  Amount
0    Ramesh  Ahmedabad     NaN     NaN
1    Khilan  Delhi       101.0  1560.0
2   kaushik  Kota        102.0  3000.0
3   kaushik  Kota        100.0  1500.0
4  Chaitali  Mumbai      103.0  2060.0
5    Hardik  Bhopal        NaN     NaN
6     Komal  MP            NaN     NaN
7     Muffy  Indore        NaN     NaN
8       NaN         NaN  199.0  1253.0

In [61]:
# 5) to join 2 dataframe with different column name (all columns) and filtering records {inner/left/right/outer}--(Completed)

In [62]:
result_df = pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "inner" )
# or)
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "inner" ).query("Name == 'kaushik'").head(10)

In [64]:
result_df.query("Name == 'kaushik'").head(10)

   ID     Name  Age     Address  Wallet Bal  OID        Date  C_ID  Amount
1   3  kaushik   25  Kota             12000  102  08-10-2009   3.0    3000
2   3  kaushik   25  Kota             12000  100  08-10-2009   3.0    1500

In [63]:
type(result_df)

pandas.core.frame.DataFrame

In [65]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "left" ).query("Name == 'kaushik'").head(10)

   ID     Name  Age     Address  Wallet Bal    OID        Date  C_ID  Amount
2   3  kaushik   25  Kota             12000  102.0  08-10-2009   3.0  3000.0
3   3  kaushik   25  Kota             12000  100.0  08-10-2009   3.0  1500.0

In [66]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "right" ).query("Name == 'kaushik'").head(10)

    ID     Name   Age     Address  Wallet Bal  OID        Date  C_ID  Amount
0  3.0  kaushik  25.0  Kota           12000.0  102  08-10-2009   3.0    3000
1  3.0  kaushik  25.0  Kota           12000.0  100  08-10-2009   3.0    1500

In [67]:
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "outer" ).query("Name == 'kaushik'").head(10)

    ID     Name   Age     Address  Wallet Bal    OID        Date  C_ID  Amount
2  3.0  kaushik  25.0  Kota           12000.0  102.0  08-10-2009   3.0  3000.0
3  3.0  kaushik  25.0  Kota           12000.0  100.0  08-10-2009   3.0  1500.0

In [68]:
# 6) to join 2 dataframe with different column name (selected columns) and filtering records {inner/left/right/outer}--(Completed)

In [69]:
# inner join
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "inner" )[["Name","Address","OID","Amount"]].query("Name == 'kaushik'").head(10)

      Name     Address  OID  Amount
1  kaushik  Kota        102    3000
2  kaushik  Kota        100    1500

In [70]:
# left join
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "left" )[["Name","Address","OID","Amount"]].query("Name == 'kaushik'").head(10)

      Name     Address    OID  Amount
2  kaushik  Kota        102.0  3000.0
3  kaushik  Kota        100.0  1500.0

In [71]:
# right join
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "right" )[["Name","Address","OID","Amount"]].query("Name == 'kaushik'").head(10)

      Name     Address  OID  Amount
0  kaushik  Kota        102    3000
1  kaushik  Kota        100    1500

In [72]:
# outer/full join
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "outer" )[["Name","Address","OID","Amount"]].query("Name == 'kaushik'").head(10)

      Name     Address    OID  Amount
2  kaushik  Kota        102.0  3000.0
3  kaushik  Kota        100.0  1500.0

In [73]:
# inner join 
# keeping the selected columns before the head 
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "inner" ).query("Name == 'kaushik'")[["Name","Address","OID","Amount"]].head(10)

      Name     Address  OID  Amount
1  kaushik  Kota        102    3000
2  kaushik  Kota        100    1500

In [76]:
# to find is null values
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "left" )[["Name","Address","OID","Amount"]].query("OID.isnull()").head(10)

     Name     Address  OID  Amount
0  Ramesh  Ahmedabad   NaN     NaN
5  Hardik  Bhopal      NaN     NaN
6   Komal  MP          NaN     NaN
7   Muffy  Indore      NaN     NaN

In [77]:
# to find not null 
pd.merge(cust,ord, left_on = "ID",right_on = "C_ID" ,how = "left" )[["Name","Address","OID","Amount"]].query("OID.notnull()").head(10)

       Name     Address    OID  Amount
1    Khilan  Delhi       101.0  1560.0
2   kaushik  Kota        102.0  3000.0
3   kaushik  Kota        100.0  1500.0
4  Chaitali  Mumbai      103.0  2060.0