In [5]:
import pandas as pd

In [6]:
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Car_Data.csv") # to read complete data file

In [7]:
data.head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,2nd Owner

In [4]:
data[data.Year == 2015].head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,2nd Owner
7,s cross,2015,6.50,8.61,33429,Diesel,Dealer,Manual,2nd Owner
9,ciaz,2015,7.45,8.92,42367,Diesel,Dealer,Manual,2nd Owner
11,ciaz,2015,6.85,10.38,51000,Diesel,Dealer,Manual,2nd Owner
12,ciaz,2015,7.50,9.94,15000,Petrol,Dealer,Automatic,2nd Owner

In [8]:
# how many cars are there in 2014
data[data.Year == 2015][["Car_Name"]].count()   # count is aggregate function

Car_Name    61
dtype: int64

In [9]:
data[data.Year == 2016][["Car_Name"]].count()

Car_Name    50
dtype: int64

In [10]:
data.groupby('Year')[["Car_Name"]].count()

      Car_Name
Year
2003         2
2004         1
2005         4
2006         4
2007         2
2008         7
2009         6
2010        15
2011        19
2012        23
2013        33
2014        38
2015        61
2016        50
2017        35
2018         1

In [11]:
data.head(4)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner

In [13]:
data.shape

(301, 9)

In [14]:
data[data['Fuel_Type'] == 'Petrol'][["Car_Name"]].count()

Car_Name    239
dtype: int64

In [15]:
data[data['Fuel_Type'] == 'Diesel'][["Car_Name"]].count()

Car_Name    60
dtype: int64

In [16]:
data.groupby('Fuel_Type')[["Car_Name"]].count()

           Car_Name
Fuel_Type
CNG               2
Diesel           60
Petrol          239

In [17]:
data.groupby('Transmission')[["Car_Name"]].count()

              Car_Name
Transmission
Automatic           40
Manual             261

In [8]:
data.head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,2nd Owner

In [11]:
data.sort_values("Selling_Price" , ascending = True ).head(5)  # sorting from small to highest
# descending is not available in dataframes use asc = False

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
200,Bajaj Pulsar 150,2006,0.10,0.75,92233,Petrol,Individual,Manual,1st Owner
199,Honda CB Shine,2007,0.12,0.58,53000,Petrol,Individual,Manual,1st Owner
198,Bajaj Discover 125,2011,0.15,0.57,35000,Petrol,Individual,Manual,1st Owner
197,Honda CB twister,2010,0.16,0.51,33000,Petrol,Individual,Manual,1st Owner
196,Activa 3g,2008,0.17,0.52,500000,Petrol,Individual,Automatic,1st Owner

In [12]:
data.sort_values("Selling_Price" , ascending = False ).head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
86,land cruiser,2010,35.0,92.60,78000,Diesel,Dealer,Manual,1st Owner
64,fortuner,2017,33.0,36.23,6000,Diesel,Dealer,Automatic,1st Owner
63,fortuner,2015,23.5,35.96,47000,Diesel,Dealer,Automatic,1st Owner
82,innova,2017,23.0,25.39,15000,Diesel,Dealer,Automatic,1st Owner
51,fortuner,2015,23.0,30.61,40000,Diesel,Dealer,Automatic,1st Owner

In [21]:
# I want to know all the years cars which is having  > 30 cars 
# Expected output (Year |  Total_Cars)
# is the ordering is important ?

data.groupby("Year")[["Car_Name"]].count() \
    .query("Car_Name > 30") \
    .sort_values("Car_Name", ascending = False) \
    .rename(columns={"Car_Name" : "Total_Cars"})  ------> Rename of column

      Total_Cars
Year
2015          61
2016          50
2014          38
2017          35
2013          33

In [22]:
data.groupby("Year")[["Car_Name"]].count() \
    .query("Car_Name > 30") \
    .rename(columns={"Car_Name" : "Total_Cars"}) \  ------> Rename of column 
    .sort_values("Total_Cars", ascending = False)

      Total_Cars
Year
2015          61
2016          50
2014          38
2017          35
2013          33

In [23]:
data.groupby("Year")[["Car_Name"]].count() \
    .rename(columns={"Car_Name" : "Total_Cars"}) \    ------> Rename of column 
    .query("Total_Cars > 30") \
        .sort_values("Total_Cars", ascending = False)

      Total_Cars
Year
2015          61
2016          50
2014          38
2017          35
2013          33

In [39]:
# i want to see all petrol cars for every year provided it has 25 cars

data.query("Fuel_Type == 'Petrol'").groupby("Year")[["Car_Name"]].count().query("Car_Name > 25 ")
#    This query is for filterning dataset                                 ---This query for filtering result

      Car_Name
Year
2013        28
2015        45
2016        42
2017        31