In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Sample_Store_1.csv" , encoding = "ISO-8859-1")

In [4]:
type(data)

pandas.core.frame.DataFrame

In [67]:
data.shape

(9994, 21)

In [6]:
data.head(3)

,RowID,OrderID,OrderDate,ShipDate,ShipMode,CustomerID,CustomerName,Segment,Country,City,...,PostalCode,Region,ProductID,Category,Sub_Category,ProductName,Sales,Quantity,Discount,Profit
0,2698,CA-2016-145317,18-03-2016,23-03-2016,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.48,6,0.5,-1811.0784
1,6827,CA-2018-118689,02-10-2018,09-10-2018,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.95,5,0.0,8399.9760
2,8154,CA-2019-140151,23-03-2019,25-03-2019,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.96,4,0.0,6719.9808

In [7]:
data.columns

Index(['RowID', 'OrderID', 'OrderDate', 'ShipDate', 'ShipMode', 'CustomerID',
       'CustomerName', 'Segment', 'Country', 'City', 'State', 'PostalCode',
       'Region', 'ProductID', 'Category', 'Sub_Category', 'ProductName',
       'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [8]:
list(data.columns)

['RowID',
 'OrderID',
 'OrderDate',
 'ShipDate',
 'ShipMode',
 'CustomerID',
 'CustomerName',
 'Segment',
 'Country',
 'City',
 'State',
 'PostalCode',
 'Region',
 'ProductID',
 'Category',
 'Sub_Category',
 'ProductName',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [9]:
order_data = data[['Segment',
 'State',
 'Region',
 'Category',
 'Sub_Category',
 'Sales',
 'Quantity',
 'Profit']]

In [10]:
data.shape

(9994, 21)

In [11]:
order_data.shape

(9994, 8)

In [12]:
order_data.head(5)

,Segment,State,Region,Category,Sub_Category,Sales,Quantity,Profit
0,Home Office,Florida,South,Technology,Machines,22638.480,6,-1811.0784
1,Corporate,Indiana,Central,Technology,Copiers,17499.950,5,8399.9760
2,Consumer,Washington,West,Technology,Copiers,13999.960,4,6719.9808
3,Home Office,New York,East,Technology,Copiers,11199.968,4,3919.9888
4,Consumer,Delaware,East,Technology,Copiers,10499.970,3,5039.9856

In [83]:
order_data[order_data['Region'] == 'South'][['Sales']].sum()

Sales    391721.905
dtype: float64

In [75]:
order_data[order_data['Region'] == 'Central'][['Sales']].sum()

Sales    501239.8908
dtype: float64

In [25]:
order_data[order_data['Region'] == 'East'][['Sales']].sum()

Sales    678781.24
dtype: float64

In [20]:
order_data[order_data['Region'] == 'West'][['Sales']].sum()

Sales    725457.8245
dtype: float64

In [84]:
order_data['Region'].unique()  # to get all unique values in column

array(['South', 'Central', 'West', 'East'], dtype=object)

In [85]:
order_data['Region'].nunique()

4

In [86]:
order_data['Category'].unique()

array(['Technology', 'Office Supplies', 'Furniture'], dtype=object)

In [87]:
order_data['Region'].nunique()

4

In [88]:
order_data.groupby("Region")[["Sales"]].sum()

               Sales
Region
Central  501239.8908
East     678781.2400
South    391721.9050
West     725457.8245

#### How to structurise the learning?
#### 1) 1 column 1 aggregation

In [89]:
# one column one aggragation # order_data.groupby([ "Region"]).agg({"Sales":"sum"})

order_data.groupby("Category")[["Sales"]].sum()

                       Sales
Category
Furniture        741999.7953
Office Supplies  719047.0320
Technology       836154.0330

#### 2) 2 column 1 aggregation   # pass it in list of columns

In [33]:
order_data.groupby(["Category" , "Region"])[["Sales"]].sum()

                               Sales
Category        Region
Furniture       Central  163797.1638
                East     208291.2040
                South    117298.6840
                West     252612.7435
Office Supplies Central  167026.4150
                East     205516.0550
                South    125651.3130
                West     220853.2490
Technology      Central  170416.3120
                East     264973.9810
                South    148771.9080
                West     251991.8320

#### 3) one column 2 aggregations

In [36]:
order_data.groupby("Region")[["Profit","Sales"]].sum()

              Profit        Sales
Region
Central   39706.3625  501239.8908
East      91522.7800  678781.2400
South     46749.4303  391721.9050
West     108418.4489  725457.8245

#### 4) 2 aggregations 2 columns

In [38]:
order_data.groupby(["Category" , "Region"])[["Sales","Profit"]].sum()

                               Sales      Profit
Category        Region
Furniture       Central  163797.1638  -2871.0494
                East     208291.2040   3046.1658
                South    117298.6840   6771.2061
                West     252612.7435  11504.9503
Office Supplies Central  167026.4150   8879.9799
                East     205516.0550  41014.5791
                South    125651.3130  19986.3928
                West     220853.2490  52609.8490
Technology      Central  170416.3120  33697.4320
                East     264973.9810  47462.0351
                South    148771.9080  19991.8314
                West     251991.8320  44303.6496

#### 5 ) Average sales of a column

In [41]:
order_data.groupby("Region")[["Sales"]].mean()   # mean is average function

              Sales
Region
Central  215.772661
East     238.336110
South    241.803645
West     226.493233

#### 5 a) One column 2 Aggregation  (one is sum one is avg)

In [45]:
order_data.groupby([ "Region"]).agg({"Sales":"sum","Profit":"mean"})

               Sales     Profit
Region
Central  501239.8908  17.092709
East     678781.2400  32.135808
South    391721.9050  28.857673
West     725457.8245  33.849032

#### 6) one column 1 aggregation with 2 diff calculations 
#### ex: for sales give sum and mean

In [47]:
# order_data.groupby([ "Region"]).agg({"Sales":"sum","Sales":"mean"}) {This wont work bcz same keys for 2 diff values}

order_data.groupby([ "Region"]).agg({"Sales":["sum","mean"]})

               Sales
                 sum        mean
Region
Central  501239.8908  215.772661
East     678781.2400  238.336110
South    391721.9050  241.803645
West     725457.8245  226.493233

#### 7) Rename column names 
#### syntax : .rename(columns= {"Sales" : "Total_Sales"})

In [49]:
order_data.groupby("Category")[["Sales"]].sum().rename(columns= {"Sales" : "Total_Sales"})

                 Total_Sales
Category
Furniture        741999.7953
Office Supplies  719047.0320
Technology       836154.0330

In [141]:
order_data.groupby([ "Region"])  \
        .agg({"Sales":["sum","mean"]}) \
        .rename(columns = {"sum" : "Total_Sales" ,"mean" : "Avg_Sales"}) 
        ##.sort_values("Total_Sales" , ascending = False)

               Sales
         Total_Sales   Avg_Sales
Region
Central  501239.8908  215.772661
East     678781.2400  238.336110
South    391721.9050  241.803645
West     725457.8245  226.493233

In [57]:
order_data.groupby("Sub_Category")[["Sales"]].sum()

                    Sales
Sub_Category
Accessories   167380.3180
Appliances    107532.1610
Art            27118.7920
Binders       203412.7330
Bookcases     114879.9963
Chairs        328449.1030
Copiers       149528.0300
Envelopes      16476.4020
Fasteners       3024.2800
Furnishings    91705.1640
Labels         12486.3120
Machines      189238.6310
Paper          78479.2060
Phones        330007.0540
Storage       223843.6080
Supplies       46673.5380
Tables        206965.5320

In [59]:
order_data["Sub_Category"].nunique()

17

In [63]:
order_data.groupby("Sub_Category")[["Sales"]].sum().query("Sales > 200000")  
# filter on top of group by

                   Sales
Sub_Category
Binders       203412.733
Chairs        328449.103
Phones        330007.054
Storage       223843.608
Tables        206965.532

In [78]:
order_data.groupby("Sub_Category")[["Sales"]].sum().query("Sales > 2000")

                    Sales
Sub_Category
Accessories   167380.3180
Appliances    107532.1610
Art            27118.7920
Binders       203412.7330
Bookcases     114879.9963
Chairs        328449.1030
Copiers       149528.0300
Envelopes      16476.4020
Fasteners       3024.2800
Furnishings    91705.1640
Labels         12486.3120
Machines      189238.6310
Paper          78479.2060
Phones        330007.0540
Storage       223843.6080
Supplies       46673.5380
Tables        206965.5320

In [91]:
order_data.groupby("Sub_Category")[["Sales"]].sum()
## Find the top 5 highest subcategory from highest to lowest

                    Sales
Sub_Category
Accessories   167380.3180
Appliances    107532.1610
Art            27118.7920
Binders       203412.7330
Bookcases     114879.9963
Chairs        328449.1030
Copiers       149528.0300
Envelopes      16476.4020
Fasteners       3024.2800
Furnishings    91705.1640
Labels         12486.3120
Machines      189238.6310
Paper          78479.2060
Phones        330007.0540
Storage       223843.6080
Supplies       46673.5380
Tables        206965.5320

In [95]:
#Sorting happend in Descending Order

order_data.groupby("Sub_Category")[["Sales"]].sum().sort_values("Sales" , ascending = False).head(5)

                   Sales
Sub_Category
Phones        330007.054
Chairs        328449.103
Storage       223843.608
Tables        206965.532
Binders       203412.733

In [98]:
# sort by ascending order 

order_data.groupby("Sub_Category")[["Sales"]].sum().sort_values("Sales" , ascending = True).head(5)

                  Sales
Sub_Category
Fasteners      3024.280
Labels        12486.312
Envelopes     16476.402
Art           27118.792
Supplies      46673.538

In [99]:
order_data.head(5)

,Segment,State,Region,Category,Sub_Category,Sales,Quantity,Profit
0,Home Office,Florida,South,Technology,Machines,22638.480,6,-1811.0784
1,Corporate,Indiana,Central,Technology,Copiers,17499.950,5,8399.9760
2,Consumer,Washington,West,Technology,Copiers,13999.960,4,6719.9808
3,Home Office,New York,East,Technology,Copiers,11199.968,4,3919.9888
4,Consumer,Delaware,East,Technology,Copiers,10499.970,3,5039.9856

In [100]:
# i want to see tot sales and tot profit for all subcategories for south region

In [131]:
order_data.query("Region == 'South'").groupby("Sub_Category").agg({"Sales":"sum", "Profit":"sum"}).reset_index()

   Sub_Category      Sales      Profit
0   Accessories  27276.754   7004.5424
1    Appliances  19525.326   4123.9396
2           Art   4655.622   1058.5866
3       Binders  37030.341   3900.6640
4     Bookcases  10899.362   1339.4918
5        Chairs  45176.446   6612.0893
6       Copiers   9299.756   3658.9067
7     Envelopes   3345.556   1465.4770
8     Fasteners    503.316    173.7181
9   Furnishings  17306.684   3442.6829
10       Labels   2353.180   1040.7723
11     Machines  53890.960  -1438.8930
12        Paper  14150.984   5947.0614
13       Phones  58304.438  10767.2753
14      Storage  35768.060   2274.2965
15     Supplies   8318.928      1.8773
16       Tables  43916.192  -4623.0579

In [ ]:
# i want to see tot sales and avg sales for segment and region wise 
# expected output 

# segment | region | tot_sales | avg sales  ( reset_index will work)

# reset index will work only for diff columns

In [ ]:
order_data.groupby(["Segment","Region"]) \
          .agg({"Sales":["sum","mean"]}) \
          .rename(columns = {"sum":"TOT_SALES", "mean":"Avg_sales"}) \
          .sort_values("TOT_SALES", ascending = False)                      # this quey is correct but cannot sort

In [ ]:
order_data.groupby(["Segment","Region"]) \
          .agg({"Sales":["sum","mean"]})\
            .rename(columns = {"sum":"TOT_SALES", "mean":"Avg_sales"}).reset_index() 
           # .sort_values("TOT_SALES", ascending = False) 


# this is not looking like table

In [33]:
order_data.groupby(["Segment", "Region"]) \
    .agg(
        TOT_SALES=("Sales", "sum"),        # directly renaming the column can avoid Rename 
        Avg_sales=("Sales", "mean")        # directly renaming the column
    ) \
    .reset_index() \
    .sort_values("TOT_SALES", ascending=False)

        Segment   Region    TOT_SALES   Avg_sales
3      Consumer     West  362880.7730  217.033955
1      Consumer     East  350908.1670  238.875539
0      Consumer  Central  252031.4340  207.946728
7     Corporate     West  225855.2745  235.265911
5     Corporate     East  200409.3470  228.516929
2      Consumer    South  195580.9710  233.390180
4     Corporate  Central  157995.8128  234.763466
11  Home Office     West  136721.7770  239.442692
9   Home Office     East  127463.7260  253.911805
6     Corporate    South  121885.9325  238.992025
8   Home Office  Central   91212.6440  208.248046
10  Home Office    South   74255.0015  272.996329

In [124]:
result = order_data.groupby("Category")[["Sales"]].sum()

In [117]:
type(result)

pandas.core.frame.DataFrame

In [118]:
result.head(5)

                       Sales
Category
Furniture        741999.7953
Office Supplies  719047.0320
Technology       836154.0330

In [120]:
result.shape

(3, 1)

In [121]:
# index is not a part of row it is just to address

In [123]:
order_data.groupby("Category")[["Sales"]].sum().reset_index()

          Category        Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [13]:
order_data.head(5)

,Segment,State,Region,Category,Sub_Category,Sales,Quantity,Profit
0,Home Office,Florida,South,Technology,Machines,22638.480,6,-1811.0784
1,Corporate,Indiana,Central,Technology,Copiers,17499.950,5,8399.9760
2,Consumer,Washington,West,Technology,Copiers,13999.960,4,6719.9808
3,Home Office,New York,East,Technology,Copiers,11199.968,4,3919.9888
4,Consumer,Delaware,East,Technology,Copiers,10499.970,3,5039.9856

In [14]:
# i want total_sales , Avg_Profit of each subcategory (only for west region)
# only subcategories which has more than 20000 sales hig to low of highest profit

In [ ]:
order_data[order_data['Region'] == 'West'] \
          .groupby("Sub_Category")  \
        .agg({"Sales":"sum","Profit":"mean"}) \
        .rename(columns = {"Sales":"Total_Sales" ,"Profit":"Average_Profit"}) \
        .query("Total_Sales > 20000") \
        .sort_values("Average_Profit", ascending = False)

In [32]:
order_data.query("Region == 'West'") \
          .groupby("Sub_Category")  \
          .agg({"Sales":"sum","Profit":"mean"}) \
          .rename(columns = {"Sales":"Total_Sales" ,"Profit":"Average_Profit"}) \
          .query("Total_Sales > 20000") \
          .sort_values("Average_Profit", ascending = False).reset_index()

   Sub_Category  Total_Sales  Average_Profit
0       Copiers   49749.2420      773.089404
1   Accessories   61114.1160       63.893792
2    Appliances   30236.3360       60.744632
3       Binders   55961.1130       34.175800
4        Phones   98684.3520       32.890768
5       Storage   70532.8520       32.501211
6         Paper   26663.7180       26.931636
7   Furnishings   30072.7300       25.135758
8        Chairs  101781.3280       19.456929
9        Tables   84754.5620       12.781097
10     Machines   42444.1220      -15.869908
11    Bookcases   36004.1235      -20.581396

In [34]:
order_data.groupby(["Segment", "Region"]) \
    .agg(
        TOT_SALES=("Sales", "sum"),        # directly renaming the column can avoid Rename 
        Avg_sales=("Sales", "mean")        # directly renaming the column
    ) \
    .reset_index()

        Segment   Region    TOT_SALES   Avg_sales
0      Consumer  Central  252031.4340  207.946728
1      Consumer     East  350908.1670  238.875539
2      Consumer    South  195580.9710  233.390180
3      Consumer     West  362880.7730  217.033955
4     Corporate  Central  157995.8128  234.763466
5     Corporate     East  200409.3470  228.516929
6     Corporate    South  121885.9325  238.992025
7     Corporate     West  225855.2745  235.265911
8   Home Office  Central   91212.6440  208.248046
9   Home Office     East  127463.7260  253.911805
10  Home Office    South   74255.0015  272.996329
11  Home Office     West  136721.7770  239.442692

In [ ]:
# i want to get tot_sales ,avg_sales for every region and state  only for technology category 
# make sure sales should be more than 20 k sort it highest to lowest avg sales

In [46]:
order_data.query("Category == 'Technology'") \
         .groupby(["State", "Region"])  \
        .agg(TOT_SALES=("Sales", "sum"), Avg_sales=("Sales", "mean") ) \
        .query("TOT_SALES > 20000").reset_index() \
         .sort_values("Avg_sales", ascending = False).head(5)

            State   Region   TOT_SALES   Avg_sales
3         Indiana  Central   26323.250  907.698276
1         Florida    South   46968.036  680.696174
9        Virginia    South   24145.160  670.698889
4        New York     East  127483.500  612.901442
5  North Carolina    South   26083.119  511.433706