In [1]:
import pandas as pd
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\investment_banking.csv")

In [ ]:
# Data Validation

In [3]:
data.head(3)

,broker_id,city,broker_type,fund_category,email_opened,webex_meet,sales_call,firm_sales,global_sales
0,BRXX-1,"PLANTATION, FL",Inter-dealer broker,Emerging-Markets Local-Currency Bond,NaN,NaN,NaN,174.62,174.62
1,BRXX-1,"BRANFORD, CT",Inter-dealer broker,Utilities,NaN,NaN,NaN,0.00,0.00
2,BRXX-1,"JONESBORO, GA",Inter-dealer broker,Intermediate Government,NaN,NaN,NaN,0.00,0.00

In [4]:
data.shape  # 7.5 lakh transactions

(753089, 9)

In [5]:
data['broker_id'].nunique()

1178

In [8]:
# req: How many loyal brockers are there among these ? 1178

In [6]:
# missing value count (i.e, COunt of null values)
data.isna().sum()

broker_id             0
city                  0
broker_type           0
fund_category         0
email_opened     434545
webex_meet       667429
sales_call       573091
firm_sales            0
global_sales          0
dtype: int64

In [7]:
# missing value % 
(data.isna().sum() / data.shape[0]) * 100

broker_id         0.000000
city              0.000000
broker_type       0.000000
fund_category     0.000000
email_opened     57.701679
webex_meet       88.625514
sales_call       76.098708
firm_sales        0.000000
global_sales      0.000000
dtype: float64

In [ ]:
# as per rule need to drop % is above 70%
# as per business knowledge should not do it need to confirm with Client

In [8]:
data['webex_meet'].unique()

array([nan, 'Y'], dtype=object)

In [12]:
data['sales_call'].unique()

array([nan, 'Y'], dtype=object)

In [13]:
data['email_opened'].unique()

array([nan, 'Y'], dtype=object)

In [15]:
# 'Yes' / 'No'  / 'MayBe' / NaN ---> 70 %
# in this we are not going to drop the column instead we are going to fill null with 'No'

In [9]:
# Missing value Treatment 
data['webex_meet'] = data['webex_meet'].fillna("N")
data['sales_call'] = data['sales_call'].fillna("N")
data['email_opened'] = data['email_opened'].fillna("N")

In [10]:
data.head(11)

,broker_id,city,broker_type,fund_category,email_opened,webex_meet,sales_call,firm_sales,global_sales
0,BRXX-1,"PLANTATION, FL",Inter-dealer broker,Emerging-Markets Local-Currency Bond,N,N,N,174.62,174.62
1,BRXX-1,"BRANFORD, CT",Inter-dealer broker,Utilities,N,N,N,0.00,0.00
2,BRXX-1,"JONESBORO, GA",Inter-dealer broker,Intermediate Government,N,N,N,0.00,0.00
3,BRXX-2,"VIENNA, VA",Inter-dealer broker,Intermediate Government,Y,N,N,0.00,30709.00
4,BRXX-3,"CHAGRIN FALLS, OH",full-service broker,Target-Date 2050,Y,N,Y,0.00,0.00
5,BRXX-2,"CARLSBAD, CA",Inter-dealer broker,Multicurrency,Y,N,N,0.00,0.00
6,BRXX-3,"BELLEVUE, WA",full-service broker,Target-Date Retirement,Y,Y,Y,0.00,5360.07
7,BRXX-1,"OWINGS MILLS, MD",Inter-dealer broker,World Large Stock,N,N,N,0.00,4807.68
8,BRXX-3,"SUMMIT, NJ",full-service broker,Intermediate-Term Bond,Y,N,Y,0.00,354219.62
9,BRXX-3,"CHARLESTON, SC",full-service broker,Convertibles,Y,N,Y,0.00,301974.77
10,BRXX-3,"EUGENE, OR",full-service broker,Foreign Small/Mid Growth,Y,Y,Y,0.00,0.00

In [11]:
# missing value % after the null values filling
(data.isna().sum() / data.shape[0]) * 100

broker_id        0.0
city             0.0
broker_type      0.0
fund_category    0.0
email_opened     0.0
webex_meet       0.0
sales_call       0.0
firm_sales       0.0
global_sales     0.0
dtype: float64

In [ ]:
# how many inter-dealer brokers and full service brokers

In [12]:
data.groupby(['broker_type'])[['broker_id']].nunique()

                     broker_id
broker_type
Inter-dealer broker       1173
full-service broker          5

In [13]:
data[['city']].head(5)

                city
0     PLANTATION, FL
1       BRANFORD, CT
2      JONESBORO, GA
3         VIENNA, VA
4  CHAGRIN FALLS, OH

In [ ]:
# Here want to split the city and state so that we need to create seperate column

In [23]:
data.shape

(753089, 9)

In [15]:
data[["city" , "state"]] = data['city'].str.split("," , n =1 , expand = True) # splitting the column

In [16]:
data.shape

(753089, 10)

In [17]:
#check any spaces or special characters / numeric values are ther in the dataframe for state 
data.head(4)

,broker_id,city,broker_type,fund_category,email_opened,webex_meet,sales_call,firm_sales,global_sales,state
0,BRXX-1,PLANTATION,Inter-dealer broker,Emerging-Markets Local-Currency Bond,N,N,N,174.62,174.62,FL
1,BRXX-1,BRANFORD,Inter-dealer broker,Utilities,N,N,N,0.00,0.00,CT
2,BRXX-1,JONESBORO,Inter-dealer broker,Intermediate Government,N,N,N,0.00,0.00,GA
3,BRXX-2,VIENNA,Inter-dealer broker,Intermediate Government,Y,N,N,0.00,30709.00,VA

In [18]:
data['state'].nunique()

60

In [29]:
data['state'].unique() # here while splitting extra space is occuring in State column need to change

array([' FL', ' CT', ' GA', ' VA', ' OH', ' CA', ' WA', ' MD', ' NJ',
       ' SC', ' OR', ' NY', ' TX', ' NC', ' KS', ' UT', ' PA', ' AZ',
       ' TN', ' HI', ' AL', ' OK', ' MA', ' WV', ' NH', ' IN', ' MI',
       ' ME', ' MN', ' DC', ' MS', ' IL', ' LA', ' CO', ' MO', ' IA',
       ' ND', ' WI', ' KY', ' ID', ' DE', ' NM', ' RI', ' AR', ' PR',
       ' WY', ' SD', ' AK', ' MT', ' VT', ' NE', ' NV', ', MD', ', CT',
       ', WI', ' TN, TN', ', VT', ', CA', ' GU', ' DC, DC'], dtype=object)

In [19]:
data['state'] = data['state'].str.replace(' ' , '')
data['state'] = data['state'].str.replace(',' , '')
data['state'] = data['state'].str.replace('TNTN' , 'TN')
data['state'] = data['state'].str.replace('DCDC' , 'DC')

In [20]:
data['state'].unique() # extra space is removed and more than 2 characters also removed

array(['FL', 'CT', 'GA', 'VA', 'OH', 'CA', 'WA', 'MD', 'NJ', 'SC', 'OR',
       'NY', 'TX', 'NC', 'KS', 'UT', 'PA', 'AZ', 'TN', 'HI', 'AL', 'OK',
       'MA', 'WV', 'NH', 'IN', 'MI', 'ME', 'MN', 'DC', 'MS', 'IL', 'LA',
       'CO', 'MO', 'IA', 'ND', 'WI', 'KY', 'ID', 'DE', 'NM', 'RI', 'AR',
       'PR', 'WY', 'SD', 'AK', 'MT', 'VT', 'NE', 'NV', 'GU'], dtype=object)

In [21]:
data['state'].unique()

array(['FL', 'CT', 'GA', 'VA', 'OH', 'CA', 'WA', 'MD', 'NJ', 'SC', 'OR',
       'NY', 'TX', 'NC', 'KS', 'UT', 'PA', 'AZ', 'TN', 'HI', 'AL', 'OK',
       'MA', 'WV', 'NH', 'IN', 'MI', 'ME', 'MN', 'DC', 'MS', 'IL', 'LA',
       'CO', 'MO', 'IA', 'ND', 'WI', 'KY', 'ID', 'DE', 'NM', 'RI', 'AR',
       'PR', 'WY', 'SD', 'AK', 'MT', 'VT', 'NE', 'NV', 'GU'], dtype=object)

In [22]:
data[data['state'].str.len() > 2].count()

broker_id        0
city             0
broker_type      0
fund_category    0
email_opened     0
webex_meet       0
sales_call       0
firm_sales       0
global_sales     0
state            0
dtype: int64

In [23]:
data[data['state'].str.len() > 2].head(20) # this should never give any result

Empty DataFrame
Columns: [broker_id, city, broker_type, fund_category, email_opened, webex_meet, sales_call, firm_sales, global_sales, state]
Index: []

In [24]:
data[data['state'].str.len() > 2].head(2) # This should not have any data (unit testing)

Empty DataFrame
Columns: [broker_id, city, broker_type, fund_category, email_opened, webex_meet, sales_call, firm_sales, global_sales, state]
Index: []

In [25]:
# proof to show that this column doesnt have any number (Unit testing)
data['state'].str.isnumeric().sum()

np.int64(0)

In [26]:
data['city'].str.isnumeric().sum() # here we had numeric values in city

np.int64(37)

In [28]:
data.sort_values('city' , ascending = True).head(5)

,broker_id,city,broker_type,fund_category,email_opened,webex_meet,sales_call,firm_sales,global_sales,state
95111,BRXX-77,15801,Inter-dealer broker,World Bond,N,N,N,0.00,0.00,PA
178474,BRXX-77,15801,Inter-dealer broker,Nontraditional Bond,N,N,N,446.01,12786.01,PA
151921,BRXX-77,15801,Inter-dealer broker,Corporate Bond,N,N,N,1684.01,1684.01,PA
633459,BRXX-77,15801,Inter-dealer broker,Mid-Cap Value,N,N,N,0.00,0.00,PA
258485,BRXX-77,15801,Inter-dealer broker,Large Value,N,N,N,686.65,12590.98,PA

In [29]:
tot_numbered_city_txn = 37
tot_txn = 753089
(tot_numbered_city_txn/tot_txn )* 100 # since % is small can we ignore ? No

0.004913097920697288

In [30]:
data[data['city'].str.isnumeric()].head(10)

,broker_id,city,broker_type,fund_category,email_opened,webex_meet,sales_call,firm_sales,global_sales,state
12956,BRXX-188,64150,Inter-dealer broker,Equity Energy,N,N,N,0.00,0.00,MO
31538,BRXX-77,15801,Inter-dealer broker,World Small/Mid Stock,N,N,N,0.00,5110.16,PA
45478,BRXX-188,64150,Inter-dealer broker,Emerging Markets Bond,N,N,N,0.00,0.00,MO
95111,BRXX-77,15801,Inter-dealer broker,World Bond,N,N,N,0.00,0.00,PA
107878,BRXX-188,64150,Inter-dealer broker,Short-Term Bond,N,N,N,0.00,0.00,MO
122236,BRXX-70,95678,Inter-dealer broker,Allocation--70% to 85% Equity,N,N,N,0.00,670.64,CA
143794,BRXX-77,15801,Inter-dealer broker,Foreign Large Blend,N,N,N,160313.60,162621.11,PA
151921,BRXX-77,15801,Inter-dealer broker,Corporate Bond,N,N,N,1684.01,1684.01,PA
158007,BRXX-77,15801,Inter-dealer broker,World Large Stock,N,N,N,0.00,4117.37,PA
170498,BRXX-188,64150,Inter-dealer broker,Nontraditional Bond,N,N,N,0.00,0.00,MO

In [103]:
data[data['city'].str.isnumeric()]['city'].unique()

array([], dtype=object)

In [104]:
# replace the city's with name 
data['city'] = data['city'].str.replace("64150" , "Riverside")
data['city'] = data['city'].str.replace("15801" , "DuBios")
data['city'] = data['city'].str.replace("95678" , "Roseville")

In [105]:
data[data['city'].str.isnumeric()]['city'].unique()

array([], dtype=object)

In [56]:
data['city'].str.isnumeric().sum()

np.int64(0)

In [57]:
data['email_opened'].str.isnumeric().sum()  # this shows that email opened is non numeric

np.int64(0)

In [58]:
data[data['email_opened'].str.len() != 1].head(10) # this shows that email opened is single character

Empty DataFrame
Columns: [broker_id, city, broker_type, fund_category, email_opened, webex_meet, sales_call, firm_sales, global_sales, state]
Index: []

In [ ]:
# Assignments 
# if webex_meet and salescall are numeric and single character

In [59]:
data['webex_meet'].str.isnumeric().sum()  # this shows that webex meet is non numeric

np.int64(0)

In [60]:
data[data['webex_meet'].str.len() != 1].head(10)

Empty DataFrame
Columns: [broker_id, city, broker_type, fund_category, email_opened, webex_meet, sales_call, firm_sales, global_sales, state]
Index: []

In [61]:
data['sales_call'].str.isnumeric().sum()

np.int64(0)

In [62]:
data[data['sales_call'].str.len() != 1].head(10)

Empty DataFrame
Columns: [broker_id, city, broker_type, fund_category, email_opened, webex_meet, sales_call, firm_sales, global_sales, state]
Index: []

In [ ]:
# for every tranxaction imp validation (firm_sales <= global sales)
# global and firm sales should noty have any character

In [64]:
data.head(12)

,broker_id,city,broker_type,fund_category,email_opened,webex_meet,sales_call,firm_sales,global_sales,state
0,BRXX-1,PLANTATION,Inter-dealer broker,Emerging-Markets Local-Currency Bond,N,N,N,174.62,174.62,FL
1,BRXX-1,BRANFORD,Inter-dealer broker,Utilities,N,N,N,0.00,0.00,CT
2,BRXX-1,JONESBORO,Inter-dealer broker,Intermediate Government,N,N,N,0.00,0.00,GA
3,BRXX-2,VIENNA,Inter-dealer broker,Intermediate Government,Y,N,N,0.00,30709.00,VA
4,BRXX-3,CHAGRIN FALLS,full-service broker,Target-Date 2050,Y,N,Y,0.00,0.00,OH
5,BRXX-2,CARLSBAD,Inter-dealer broker,Multicurrency,Y,N,N,0.00,0.00,CA
6,BRXX-3,BELLEVUE,full-service broker,Target-Date Retirement,Y,Y,Y,0.00,5360.07,WA
7,BRXX-1,OWINGS MILLS,Inter-dealer broker,World Large Stock,N,N,N,0.00,4807.68,MD
8,BRXX-3,SUMMIT,full-service broker,Intermediate-Term Bond,Y,N,Y,0.00,354219.62,NJ
9,BRXX-3,CHARLESTON,full-service broker,Convertibles,Y,N,Y,0.00,301974.77,SC
10,BRXX-3,EUGENE,full-service broker,Foreign Small/Mid Growth,Y,Y,Y,0.00,0.00,OR
11,BRXX-3,NEW YORK,full-service broker,Target-Date 2045,Y,Y,Y,10880.65,71979.50,NY

In [65]:
data["firm_sales"] = pd.to_numeric(data["firm_sales"], errors="coerce")
data["global_sales"] = pd.to_numeric(data["global_sales"], errors="coerce")

In [66]:
invalid_sales = data[data["firm_sales"] > data["global_sales"]]

In [67]:
type (invalid_sales)

pandas.core.frame.DataFrame

In [68]:
invalid_sales
# it should come empty as below

Empty DataFrame
Columns: [broker_id, city, broker_type, fund_category, email_opened, webex_meet, sales_call, firm_sales, global_sales, state]
Index: []

In [69]:
invalid_sales.head(5)

Empty DataFrame
Columns: [broker_id, city, broker_type, fund_category, email_opened, webex_meet, sales_call, firm_sales, global_sales, state]
Index: []

In [70]:
invalid_datatype = data[
    data["firm_sales"].isna() | data["global_sales"].isna()
]

In [71]:
valid_data = data[
    (data["firm_sales"] <= data["global_sales"]) &
    (data["firm_sales"].notna()) &
    (data["global_sales"].notna())
]

In [72]:
valid_data

,broker_id,city,broker_type,fund_category,email_opened,webex_meet,sales_call,firm_sales,global_sales,state
0,BRXX-1,PLANTATION,Inter-dealer broker,Emerging-Markets Local-Currency Bond,N,N,N,174.62,174.62,FL
1,BRXX-1,BRANFORD,Inter-dealer broker,Utilities,N,N,N,0.00,0.00,CT
2,BRXX-1,JONESBORO,Inter-dealer broker,Intermediate Government,N,N,N,0.00,0.00,GA
3,BRXX-2,VIENNA,Inter-dealer broker,Intermediate Government,Y,N,N,0.00,30709.00,VA
4,BRXX-3,CHAGRIN FALLS,full-service broker,Target-Date 2050,Y,N,Y,0.00,0.00,OH
...,...,...,...,...,...,...,...,...,...,...
753084,BRXX-298,PARKERSBURG,Inter-dealer broker,Bank Loan,Y,N,Y,0.00,9000.00,WV
753085,BRXX-298,SOUTH GLENS FALLS,Inter-dealer broker,Mid-Cap Blend,N,N,N,12256.94,30365.02,NY
753086,BRXX-298,REDLANDS,Inter-dealer broker,Diversified Emerging Mkts,N,N,N,0.00,54.88,CA
753087,BRXX-298,CASTRO VALLEY,Inter-dealer broker,Mid-Cap Blend,N,N,N,0.00,0.00,CA
753088,BRXX-298,MONTICELLO,Inter-dealer broker,World Small/Mid Stock,N,N,Y,0.00,41174.48,IN

In [73]:
invalid_rows = data[data['firm_sales'] > data['global_sales']] # to find frim > global sales

In [74]:
invalid_rows.head(5)

Empty DataFrame
Columns: [broker_id, city, broker_type, fund_category, email_opened, webex_meet, sales_call, firm_sales, global_sales, state]
Index: []

In [75]:
data[data['broker_id']=='BRXX-100'][['firm_sales']].sum() # frim sales sum = 267918.14

firm_sales    267918.14
dtype: float64

In [76]:
data[data['broker_id']=='BRXX-100'][['global_sales']].sum() # global sales sum = 8150360.78

global_sales    8150360.78
dtype: float64

In [77]:
(267918.14/8150360.78)*100 # is loyality

3.2871936253109033

In [ ]:
# Analysis

In [78]:
data.groupby('broker_id')[['firm_sales','global_sales']].sum().reset_index()

      broker_id   firm_sales  global_sales
0        BRXX-1  11157673.73  1.066317e+08
1       BRXX-10         0.00  7.483650e+05
2      BRXX-100    267918.14  8.150361e+06
3     BRXX-1000         0.00  0.000000e+00
4     BRXX-1001         0.00  1.089745e+06
...         ...          ...           ...
1173   BRXX-995         0.00  1.812608e+04
1174   BRXX-996         0.00  3.196738e+04
1175   BRXX-997         0.00  1.655000e+05
1176   BRXX-998         0.00  0.000000e+00
1177   BRXX-999         0.00  1.287000e+04

[1178 rows x 3 columns]

In [ ]:
# to calculate loyality %

In [106]:
df = data.groupby('broker_id')[['firm_sales','global_sales']].sum().reset_index() # assign to new df (dataframe )

In [107]:
df.head(5)

   broker_id   firm_sales  global_sales
0     BRXX-1  11157673.73  1.066317e+08
1    BRXX-10         0.00  7.483650e+05
2   BRXX-100    267918.14  8.150361e+06
3  BRXX-1000         0.00  0.000000e+00
4  BRXX-1001         0.00  1.089745e+06

In [108]:
df['loyality_percentage'] = (df['firm_sales']/ df['global_sales']) * 100

In [82]:
df.shape

(1178, 4)

In [109]:
df.head(5)

   broker_id   firm_sales  global_sales  loyality_percentage
0     BRXX-1  11157673.73  1.066317e+08            10.463750
1    BRXX-10         0.00  7.483650e+05             0.000000
2   BRXX-100    267918.14  8.150361e+06             3.287194
3  BRXX-1000         0.00  0.000000e+00                  NaN
4  BRXX-1001         0.00  1.089745e+06             0.000000

In [110]:
df.sort_values('loyality_percentage', ascending = False).head(18)

      broker_id   firm_sales  global_sales  loyality_percentage
42    BRXX-1036       245.76        245.76           100.000000
8     BRXX-1005        77.23         77.23           100.000000
23    BRXX-1019      5571.97       5571.97           100.000000
621    BRXX-498     13042.03      13042.03           100.000000
858    BRXX-710     27438.30      27627.97            99.313486
895    BRXX-744   4352339.58    4389608.62            99.150971
137   BRXX-1121    754618.93     775703.36            97.281895
335     BRXX-24  15800032.61   16787455.29            94.118092
1118   BRXX-945     25429.96      27142.96            93.688971
287    BRXX-197   1000213.01    1203312.21            83.121654
195   BRXX-1174     50351.62      61164.62            82.321479
925    BRXX-771     20500.00      26500.00            77.358491
1086   BRXX-916     12552.30      16964.81            73.990219
435     BRXX-33    200000.00     302052.48            66.213659
472    BRXX-363    953965.10    1569159.31            60.794662
483    BRXX-373   1685424.37    3192805.72            52.788191
571    BRXX-452    473328.17    1039551.53            45.531958
1129   BRXX-955     53344.18     117927.30            45.234801

In [111]:
# function to add loyal category as per the percentage
def loyality_check(loyality_percentage):
    if loyality_percentage == 100:
        return "Loyal Brokers"
    elif loyality_percentage >= 85 and loyality_percentage < 100:
        return "SteadyFast Brokers"
    elif loyality_percentage >= 50 and loyality_percentage < 85:
        return "Reasonabily Devoted Brokers (Moderate)"
    elif loyality_percentage < 50 and loyality_percentage > 0:
        return "Less Inclined Brokers"
    elif loyality_percentage == 0:
        return "Non Comitted brokers"
    else:
        return "Stagent Brokers"

In [112]:
# here we are adding new column and applying function to it 
df['Loyality_category']= df['loyality_percentage'].apply(loyality_check)

In [113]:
df.head(6)

,broker_id,firm_sales,global_sales,loyality_percentage,Loyality_category
0,BRXX-1,11157673.73,1.066317e+08,10.463750,Less Inclined Brokers
1,BRXX-10,0.00,7.483650e+05,0.000000,Non Comitted brokers
2,BRXX-100,267918.14,8.150361e+06,3.287194,Less Inclined Brokers
3,BRXX-1000,0.00,0.000000e+00,NaN,Stagent Brokers
4,BRXX-1001,0.00,1.089745e+06,0.000000,Non Comitted brokers
5,BRXX-1002,29387.17,9.652822e+04,30.444123,Less Inclined Brokers

In [88]:
df.shape

(1178, 5)

In [114]:
df.groupby('Loyality_category')[['broker_id']].count().reset_index().sort_values('broker_id',ascending = False)

                        Loyality_category  broker_id
2                    Non Comitted brokers        686
0                   Less Inclined Brokers        310
4                         Stagent Brokers        166
3  Reasonabily Devoted Brokers (Moderate)          7
5                      SteadyFast Brokers          5
1                           Loyal Brokers          4

In [ ]:
# insight out of 1178 brokers , 686 brokers Never buyng our frim 
# 166 brokers never purchased anywhere

In [96]:
7+5+4

16

In [ ]:
# in this 686 brokers how many are attended to webex call and checked mail and sales call

In [90]:
df.head(5) # this is derived data frame

,broker_id,firm_sales,global_sales,loyality_percentage,Loyality_category
0,BRXX-1,11157673.73,1.066317e+08,10.463750,Less Inclined Brokers
1,BRXX-10,0.00,7.483650e+05,0.000000,Non Comitted brokers
2,BRXX-100,267918.14,8.150361e+06,3.287194,Less Inclined Brokers
3,BRXX-1000,0.00,0.000000e+00,NaN,Stagent Brokers
4,BRXX-1001,0.00,1.089745e+06,0.000000,Non Comitted brokers

In [91]:
data.head(5) # original data frame

,broker_id,city,broker_type,fund_category,email_opened,webex_meet,sales_call,firm_sales,global_sales,state
0,BRXX-1,PLANTATION,Inter-dealer broker,Emerging-Markets Local-Currency Bond,N,N,N,174.62,174.62,FL
1,BRXX-1,BRANFORD,Inter-dealer broker,Utilities,N,N,N,0.00,0.00,CT
2,BRXX-1,JONESBORO,Inter-dealer broker,Intermediate Government,N,N,N,0.00,0.00,GA
3,BRXX-2,VIENNA,Inter-dealer broker,Intermediate Government,Y,N,N,0.00,30709.00,VA
4,BRXX-3,CHAGRIN FALLS,full-service broker,Target-Date 2050,Y,N,Y,0.00,0.00,OH

In [ ]:
# to find we need the Join satatement for two df

In [115]:
final_df = pd.merge(data , df, on = "broker_id" ,how = "inner")[["broker_id","city","broker_type","email_opened","webex_meet","sales_call","state","Loyality_category"]]

In [116]:
final_df.head(2)

,broker_id,city,broker_type,email_opened,webex_meet,sales_call,state,Loyality_category
0,BRXX-1,PLANTATION,Inter-dealer broker,N,N,N,FL,Less Inclined Brokers
1,BRXX-1,BRANFORD,Inter-dealer broker,N,N,N,CT,Less Inclined Brokers

In [117]:
final_df.head(5)

,broker_id,city,broker_type,email_opened,webex_meet,sales_call,state,Loyality_category
0,BRXX-1,PLANTATION,Inter-dealer broker,N,N,N,FL,Less Inclined Brokers
1,BRXX-1,BRANFORD,Inter-dealer broker,N,N,N,CT,Less Inclined Brokers
2,BRXX-1,JONESBORO,Inter-dealer broker,N,N,N,GA,Less Inclined Brokers
3,BRXX-2,VIENNA,Inter-dealer broker,Y,N,N,VA,Non Comitted brokers
4,BRXX-3,CHAGRIN FALLS,full-service broker,Y,N,Y,OH,Less Inclined Brokers

In [118]:
final_df.groupby(["email_opened"])[["broker_id"]].count()

              broker_id
email_opened
N                434545
Y                318544

In [119]:
df1 = final_df.groupby(["email_opened","webex_meet","sales_call","broker_id"])[["broker_id"]].count().rename(columns = {"broker_id":"txn_cnt"}).reset_index()

In [120]:
df1[df1["broker_id"] == "BRXX-100"].head(10)

     email_opened webex_meet sales_call broker_id  txn_cnt
1               N          N          N  BRXX-100      160
1009            N          N          Y  BRXX-100       25
1221            Y          N          N  BRXX-100       62

In [121]:
final_df[final_df["broker_id"]=="BRXX-100"][["broker_id"]].count()

broker_id    247
dtype: int64

In [122]:
final_df[final_df["broker_id"]=="BRXX-101"][["broker_id"]].head(5)

     broker_id
3321  BRXX-101
3378  BRXX-101
3388  BRXX-101
4935  BRXX-101
7715  BRXX-101

In [123]:
df1[df1["broker_id"] == "BRXX-101"].head(10)

     email_opened webex_meet sales_call broker_id  txn_cnt
10              N          N          N  BRXX-101     1469
1010            N          N          Y  BRXX-101       12
1152            N          Y          N  BRXX-101       22
1201            N          Y          Y  BRXX-101       14
1225            Y          N          N  BRXX-101      328
1688            Y          N          Y  BRXX-101       74
1919            Y          Y          N  BRXX-101       34
2105            Y          Y          Y  BRXX-101       27

In [124]:
df1[df1["broker_id"] == "BRXX-1008"].head(10)

  email_opened webex_meet sales_call  broker_id  txn_cnt
8            N          N          N  BRXX-1008        4

In [125]:
df1[df1["broker_id"] == "BRXX-9"].head(10)

    email_opened webex_meet sales_call broker_id  txn_cnt
915            N          N          N    BRXX-9       15

In [126]:
df1[df1["broker_id"] == "BRXX-7"].head(10)

     email_opened webex_meet sales_call broker_id  txn_cnt
737             N          N          N    BRXX-7       30
1880            Y          N          Y    BRXX-7       22