In [3]:
import pandas as pd
data = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\student_info.xlsx")

In [4]:
data.head(5)

   ID      NAME  MARKS
0   1  SANTHOSH     75
1   2     KIRAN     90
2   3     ARJUN     77
3   4   KARTHIK     97
4   5     RAJEV     65

In [6]:
# to find highest marks student 
data.sort_values("MARKS", ascending = False).head(1)

   ID  NAME  MARKS
7   8  DIYA     99

In [7]:
# to find Lowest marks student 
data.sort_values("MARKS", ascending = True).head(1)

   ID   NAME  MARKS
6   7  TARUN     35

In [8]:
data.sort_values("MARKS", ascending = False).head(5)

   ID      NAME  MARKS
7   8      DIYA     99
3   4   KARTHIK     97
1   2     KIRAN     90
2   3     ARJUN     77
0   1  SANTHOSH     75

In [9]:
abc = data.sort_values("MARKS", ascending = False).head(5)

In [10]:
abc.sort_values("MARKS", ascending = True).head(1)

   ID      NAME  MARKS
0   1  SANTHOSH     75

### window Functions
### Functions where logic is applied for certain columns to derive new column

In [11]:
data.head(10)

   ID      NAME  MARKS
0   1  SANTHOSH     75
1   2     KIRAN     90
2   3     ARJUN     77
3   4   KARTHIK     97
4   5     RAJEV     65
5   6     GOPAL     65
6   7     TARUN     35
7   8      DIYA     99

In [12]:
data['Rank'] = data['MARKS'].rank(method = 'min', ascending = True)

In [13]:
data.head(10)

   ID      NAME  MARKS  Rank
0   1  SANTHOSH     75   4.0
1   2     KIRAN     90   6.0
2   3     ARJUN     77   5.0
3   4   KARTHIK     97   7.0
4   5     RAJEV     65   2.0
5   6     GOPAL     65   2.0
6   7     TARUN     35   1.0
7   8      DIYA     99   8.0

In [ ]:
# here we are getting decimal ranking do casting 
# min --> rank function
# Dense rank - rank will not be skipped
# problemm with sense rank --> not applicable for ranking systems ex: olyampics
# Row number we didnt see duplicate ranks we will get consecutive ranks

In [44]:
data['Rank'] = data['MARKS'].rank(method = 'min', ascending = False).astype('int')
data['DENSE'] = data['MARKS'].rank(method = 'dense', ascending = False).astype('int')
data['ROW_NUMBER'] = data['MARKS'].rank(method = 'first', ascending = False).astype('int')

In [45]:
data.head(10)

   ID      NAME  MARKS  Rank  DENSE  ROW_NUMBER
0   1  SANTHOSH     75     5      5           5
1   2     KIRAN     90     3      3           3
2   3     ARJUN     77     4      4           4
3   4   KARTHIK     97     2      2           2
4   5     RAJEV     65     6      6           6
5   6     GOPAL     65     6      6           7
6   7     TARUN     35     8      7           8
7   8      DIYA     99     1      1           1

In [46]:
data.sort_values("Rank", ascending = True) # rank function will skip rank incase of same rank

   ID      NAME  MARKS  Rank  DENSE  ROW_NUMBER
7   8      DIYA     99     1      1           1
3   4   KARTHIK     97     2      2           2
1   2     KIRAN     90     3      3           3
2   3     ARJUN     77     4      4           4
0   1  SANTHOSH     75     5      5           5
4   5     RAJEV     65     6      6           6
5   6     GOPAL     65     6      6           7
6   7     TARUN     35     8      7           8

In [23]:
data1 = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\Studentainfo1.xlsx")

In [24]:
data1.head(10)

   ID      NAME  MARKS
0   1  SANTHOSH     99
1   2     KIRAN     99
2   3     ARJUN     99
3   4   KARTHIK     99
4   5     RAJEV     99
5   6     GOPAL     99
6   7     TARUN     99
7   8      DIYA     97

In [47]:
data1['Rank'] = data1['MARKS'].rank(method = 'min', ascending = False).astype('int')
data1['DENSE'] = data1['MARKS'].rank(method = 'dense', ascending = False).astype('int')
data1['ROWNUMBER'] = data1['MARKS'].rank(method = 'first', ascending = False).astype('int')

In [48]:
data1.head(10)

   ID      NAME  MARKS  Rank  DENSE  ROWNUMBER
0   1  SANTHOSH     99     1      1          1
1   2     KIRAN     99     1      1          2
2   3     ARJUN     99     1      1          3
3   4   KARTHIK     99     1      1          4
4   5     RAJEV     99     1      1          5
5   6     GOPAL     99     1      1          6
6   7     TARUN     99     1      1          7
7   8      DIYA     97     8      2          8

In [49]:
data1.sort_values("Rank", ascending = True)

   ID      NAME  MARKS  Rank  DENSE  ROWNUMBER
0   1  SANTHOSH     99     1      1          1
1   2     KIRAN     99     1      1          2
2   3     ARJUN     99     1      1          3
3   4   KARTHIK     99     1      1          4
4   5     RAJEV     99     1      1          5
5   6     GOPAL     99     1      1          6
6   7     TARUN     99     1      1          7
7   8      DIYA     97     8      2          8

In [50]:
df = pd.read_excel("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\student_info1.xlsx")

In [51]:
df.head(10)

   ID      NAME   MEDIUM  MARKS
0   1  SANTHOSH  ENGLISH     75
1   2     KIRAN  KANNADA     90
2   3     ARJUN  KANNADA     77
3   4   KARTHIK  ENGLISH     97
4   5     RAJEV  ENGLISH     65
5   6     GOPAL  KANNADA     65
6   7     TARUN  ENGLISH     35
7   8      DIYA  KANNADA     99

In [52]:
df["RANK"] = df['MARKS'].rank(method = "min" , ascending = False).astype("int")

In [53]:
df.head(10)

   ID      NAME   MEDIUM  MARKS  RANK
0   1  SANTHOSH  ENGLISH     75     5
1   2     KIRAN  KANNADA     90     3
2   3     ARJUN  KANNADA     77     4
3   4   KARTHIK  ENGLISH     97     2
4   5     RAJEV  ENGLISH     65     6
5   6     GOPAL  KANNADA     65     6
6   7     TARUN  ENGLISH     35     8
7   8      DIYA  KANNADA     99     1

In [54]:
df["RANK"] = df.groupby(['MEDIUM'])['MARKS'].rank(method = 'min' , ascending = False).astype("int")

In [56]:
df.sort_values("MEDIUM" , ascending = True ).head(10)

   ID      NAME   MEDIUM  MARKS  RANK
0   1  SANTHOSH  ENGLISH     75     2
3   4   KARTHIK  ENGLISH     97     1
4   5     RAJEV  ENGLISH     65     3
6   7     TARUN  ENGLISH     35     4
1   2     KIRAN  KANNADA     90     2
2   3     ARJUN  KANNADA     77     3
5   6     GOPAL  KANNADA     65     4
7   8      DIYA  KANNADA     99     1

In [ ]:
# important Topic YoY

In [80]:
sales = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\sales_info.csv")

In [81]:
sales.head(5)

   C_Year  T_Sales
0    2014    25000
1    2016    18000
2    2017    23500
3    2015    12500
4    2012    17500

### YoY % = ((Current Year Sales - previous Year sales)/previous Year sales ) * 100

In [85]:
sales = sales.sort_values("C_Year" , ascending = True)

In [86]:
sales['PY_Sales'] = sales['T_Sales'].shift(1)  # shift will create 1 step lag as follows

In [87]:
sales.head(10)

   C_Year  T_Sales  PY_Sales
4    2012    17500       NaN
5    2013    15000   17500.0
0    2014    25000   15000.0
3    2015    12500   25000.0
1    2016    18000   12500.0
2    2017    23500   18000.0

In [88]:
sales['YoY'] = ((sales['T_Sales'] - sales['PY_Sales'])/ sales['PY_Sales']) * 100

In [89]:
sales.head(10)

   C_Year  T_Sales  PY_Sales        YoY
4    2012    17500       NaN        NaN
5    2013    15000   17500.0 -14.285714
0    2014    25000   15000.0  66.666667
3    2015    12500   25000.0 -50.000000
1    2016    18000   12500.0  44.000000
2    2017    23500   18000.0  30.555556

In [102]:
sales1 = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\sales_info1.csv")

In [103]:
sales1.head(10)

   C_Year   Deptmant  T_Sales
0    2014  Marketing    25000
1    2016  Marketing    18000
2    2017  Marketing    23500
3    2015  Marketing    12500
4    2012  Marketing    17500
5    2013  Marketing    15000
6    2014      Sales    24000
7    2016      Sales    21000
8    2017      Sales    19000
9    2015      Sales    17000

In [104]:
sales1 = sales1.sort_values("C_Year" , ascending = True)

In [105]:
sales1.head(10)

    C_Year   Deptmant  T_Sales
4     2012  Marketing    17500
10    2012      Sales    13500
5     2013  Marketing    15000
11    2013      Sales    12000
0     2014  Marketing    25000
6     2014      Sales    24000
3     2015  Marketing    12500
9     2015      Sales    17000
1     2016  Marketing    18000
7     2016      Sales    21000

In [98]:
sales1['PY_Sales'] = sales1['T_Sales'].shift(1) # this is wrong bcoz we have dept column so it gives wrong

In [99]:
sales1.head(5)

    C_Year   Deptmant  T_Sales  PY_Sales         YoY
4     2012  Marketing    17500       NaN         NaN
10    2012      Sales    13500       NaN  -22.857143
5     2013  Marketing    15000   17500.0   11.111111
11    2013      Sales    12000   13500.0  -20.000000
0     2014  Marketing    25000   15000.0  108.333333

In [100]:
sales1['YoY'] = ((sales1['T_Sales'] - sales1['PY_Sales'])/ sales1['PY_Sales']) * 100

In [101]:
sales1.head(10)

    C_Year   Deptmant  T_Sales  PY_Sales         YoY
4     2012  Marketing    17500       NaN         NaN
10    2012      Sales    13500       NaN         NaN
5     2013  Marketing    15000   17500.0  -14.285714
11    2013      Sales    12000   13500.0  -11.111111
0     2014  Marketing    25000   15000.0   66.666667
6     2014      Sales    24000   12000.0  100.000000
3     2015  Marketing    12500   25000.0  -50.000000
9     2015      Sales    17000   24000.0  -29.166667
1     2016  Marketing    18000   12500.0   44.000000
7     2016      Sales    21000   17000.0   23.529412

In [106]:
sales1['PY_Sales'] = sales1.groupby('Deptmant')['T_Sales'].shift(1) # by using group by we can do it

In [107]:
sales1['YoY'] = (
    (sales1['T_Sales'] - sales1['PY_Sales'])
    / sales1['PY_Sales']
) * 100

In [108]:
sales1.head(10)

    C_Year   Deptmant  T_Sales  PY_Sales         YoY
4     2012  Marketing    17500       NaN         NaN
10    2012      Sales    13500       NaN         NaN
5     2013  Marketing    15000   17500.0  -14.285714
11    2013      Sales    12000   13500.0  -11.111111
0     2014  Marketing    25000   15000.0   66.666667
6     2014      Sales    24000   12000.0  100.000000
3     2015  Marketing    12500   25000.0  -50.000000
9     2015      Sales    17000   24000.0  -29.166667
1     2016  Marketing    18000   12500.0   44.000000
7     2016      Sales    21000   17000.0   23.529412

In [109]:
df = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\sales_info1.csv")

In [110]:
df = df.sort_values(["C_Year","Deptmant"])

In [111]:
df['PY_sales'] = df.groupby('Deptmant')[['T_Sales']].shift(1)

In [112]:
df.head(10)

    C_Year   Deptmant  T_Sales  PY_sales
4     2012  Marketing    17500       NaN
10    2012      Sales    13500       NaN
5     2013  Marketing    15000   17500.0
11    2013      Sales    12000   13500.0
0     2014  Marketing    25000   15000.0
6     2014      Sales    24000   12000.0
3     2015  Marketing    12500   25000.0
9     2015      Sales    17000   24000.0
1     2016  Marketing    18000   12500.0
7     2016      Sales    21000   17000.0

In [ ]:
# Alternate Way

In [113]:
df = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\sales_info.csv")

In [114]:
df.head(10)

   C_Year  T_Sales
0    2014    25000
1    2016    18000
2    2017    23500
3    2015    12500
4    2012    17500
5    2013    15000

In [115]:
df['YoY'] = df['T_Sales'].pct_change() * 100

In [116]:
df.head(10)

   C_Year  T_Sales        YoY
0    2014    25000        NaN
1    2016    18000 -28.000000
2    2017    23500  30.555556
3    2015    12500 -46.808511
4    2012    17500  40.000000
5    2013    15000 -14.285714

In [117]:
df1 = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\sales_info1.csv")

In [119]:
df1 = df1.sort_values(["C_Year","Deptmant"])

In [120]:
df1.head(10)

    C_Year   Deptmant  T_Sales
4     2012  Marketing    17500
10    2012      Sales    13500
5     2013  Marketing    15000
11    2013      Sales    12000
0     2014  Marketing    25000
6     2014      Sales    24000
3     2015  Marketing    12500
9     2015      Sales    17000
1     2016  Marketing    18000
7     2016      Sales    21000

In [123]:
df1['YoY'] = df1.groupby('Deptmant')['T_Sales'].pct_change() * 100

In [124]:
df1.head(10)

    C_Year   Deptmant  T_Sales         YoY
4     2012  Marketing    17500         NaN
10    2012      Sales    13500         NaN
5     2013  Marketing    15000  -14.285714
11    2013      Sales    12000  -11.111111
0     2014  Marketing    25000   66.666667
6     2014      Sales    24000  100.000000
3     2015  Marketing    12500  -50.000000
9     2015      Sales    17000  -29.166667
1     2016  Marketing    18000   44.000000
7     2016      Sales    21000   23.529412