In [3]:
import pandas as pd

#### pandas -> library (data manipulation, analysis & cleaning)
#### pandas -> panel Data (python data analysis)
#### pandas -> can analyze data , can do calculations ,manipulate, read files (diff sources)

In [4]:
d1 = {
    "Car_Name" : "BMW",
    "Year" : 2017,
    "Fuel_Type":"Petrol"
}

In [5]:
d1 = {
    "Car_Name" : ["ritz", "sX4", "ciaz"],
    "Year" : [2017,2013,2014],
    "Fuel_Type":["Petrol" , "Diesel" , "Petrol"]
}

# problem with Dictonary --> Analysis become difficult

In [6]:
# how to access 2013
d1['Year']

[2017, 2013, 2014]

In [7]:
d1['Year'][1]

2013

In [10]:
# Data type is only applicable inside this library called as pandas

In [7]:
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\SQL\\Data_Sets\\Car_Data.csv") # to read complete data file

In [ ]:
data1 = 16
data2 = "KSR"
data3 = 5.6
data4 = [56,16,28]
data5 = ("KSR" , 2019)
data6 = {"Institute":"KSR" , "Founded": 2018}
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI DATA_ENGINEERING\\SQL\\Data_Sets\\Car_Data.csv")

In [23]:
#type(data1)
#type(data2)
#type(data3)
#type(data4)
#type(data5)
#type(data6)
type(data)

pandas.core.frame.DataFrame

In [10]:
data.head(3)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner

In [20]:
# dataframe(datatype) --> It is a 2 dimentional table like structure (rows and columns)
#                     --> This dataframe can be relate to spreadsheet/csv/sql

In [26]:
type(data)

pandas.core.frame.DataFrame

In [27]:
data.head()  # this is function

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,2nd Owner

In [29]:
data.head(2)  # first 2 records

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,1st Owner

In [ ]:
# any functions do open and close brackets

In [32]:
data.tail(3) # last 3 records

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
298,city,2009,3.35,11.0,87934,Petrol,Dealer,Manual,1st Owner
299,city,2017,11.50,12.5,9000,Diesel,Dealer,Manual,1st Owner
300,brio,2016,5.30,5.9,5464,Petrol,Dealer,Manual,1st Owner

In [34]:
# count of complete records in data set
data.shape   # this is instance it will be total row count and column count
            # result looks like tuple
            # used in documentation purpose

(301, 9)

In [35]:
data.shape[0]  # only row count

301

In [36]:
data.shape[1]  # only column count

9

In [37]:
print("The data set has ", data.shape[0], "rows")

The data set has  301 rows

In [38]:
data.columns  # to get all the column names  This is instance

Index(['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Kms_Driven',
       'Fuel_Type', 'Seller_Type', 'Transmission', 'Car_Owner'],
      dtype='object')

In [39]:
# to find internal datatype of columns
data.dtypes

Car_Name          object
Year               int64
Selling_Price    float64
Present_Price    float64
Kms_Driven         int64
Fuel_Type         object
Seller_Type       object
Transmission      object
Car_Owner         object
dtype: object

In [41]:
data.head(3)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner

In [43]:
data[data['Year'] == 2014].head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,2nd Owner
23,alto k10,2014,2.50,3.46,45280,Petrol,Dealer,Manual,1st Owner
32,swift,2014,4.95,7.49,39000,Diesel,Dealer,Manual,1st Owner
33,ertiga,2014,6.00,9.95,45000,Diesel,Dealer,Manual,1st Owner

In [46]:
data[data['Fuel_Type'] == 'Petrol'].head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,2nd Owner
10,alto 800,2017,2.85,3.60,2135,Petrol,Dealer,Manual,2nd Owner

In [50]:
# multiple filters give & condition and encloge with closed brackets
data[(data['Year'] == 2014) & (data['Fuel_Type'] == 'Petrol')]

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.590,27000,Petrol,Dealer,Manual,1st Owner
23,alto k10,2014,2.50,3.460,45280,Petrol,Dealer,Manual,1st Owner
41,alto k10,2014,2.55,3.980,46706,Petrol,Dealer,Manual,1st Owner
45,ciaz,2014,7.50,12.040,15000,Petrol,Dealer,Automatic,1st Owner
58,etios g,2014,4.10,6.800,39485,Petrol,Dealer,Manual,1st Owner
89,etios g,2014,4.75,6.760,40000,Petrol,Dealer,Manual,1st Owner
106,Hyosung GT250R,2014,1.35,3.450,16500,Petrol,Individual,Manual,1st Owner
112,KTM 390 Duke,2014,1.15,2.400,7000,Petrol,Individual,Manual,1st Owner
136,Honda CBR 150,2014,0.65,1.200,23500,Petrol,Individual,Manual,1st Owner
144,Bajaj Pulsar NS 200,2014,0.60,0.990,25000,Petrol,Individual,Manual,1st Owner
146,Hero Extreme,2014,0.55,0.787,15000,Petrol,Individual,Manual,1st Owner
154,Yamaha Fazer,2014,0.50,0.880,8000,Petrol,Individual,Manual,1st Owner
161,TVS Apache RTR 180,2014,0.45,0.826,23000,Petrol,Individual,Manual,1st Owner
167,TVS Apache RTR 160,2014,0.42,0.810,42000,Petrol,Individual,Manual,1st Owner
172,Bajaj Pulsar 135 LS,2014,0.40,0.640,13700,Petrol,Individual,Manual,1st Owner
178,TVS Jupyter,2014,0.35,0.520,19000,Petrol,Individual,Automatic,1st Owner
218,verna,2014,6.45,9.400,45078,Petrol,Dealer,Manual,1st Owner
242,xcent,2014,4.40,7.130,34000,Petrol,Dealer,Manual,1st Owner
259,amaze,2014,3.90,7.000,36054,Petrol,Dealer,Manual,1st Owner
266,amaze,2014,3.65,7.000,35000,Petrol,Dealer,Manual,1st Owner
274,brio,2014,5.30,6.800,16500,Petrol,Dealer,Manual,1st Owner
279,city,2014,6.25,13.600,40126,Petrol,Dealer,Manual,1st Owner
290,amaze,2014,4.50,6.400,19000,Petrol,Dealer,Manual,1st Owner
294,amaze,2014,3.75,6.800,33019,Petrol,Dealer,Manual,1st Owner

In [51]:
data[(data['Year'] == 2014) & (data['Fuel_Type'] == 'Petrol') & (data['Transmission'] == 'Automatic')]

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
45,ciaz,2014,7.50,12.04,15000,Petrol,Dealer,Automatic,1st Owner
178,TVS Jupyter,2014,0.35,0.52,19000,Petrol,Individual,Automatic,1st Owner

In [53]:
data[(data['Year'] == 2017) & (data["Seller_Type"] == 'Individual' )].head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
27,swift,2017,6.00,6.49,16200,Petrol,Individual,Manual,1st Owner
101,UM Renegade Mojave,2017,1.70,1.82,1400,Petrol,Individual,Manual,1st Owner
102,KTM RC200,2017,1.65,1.78,4000,Petrol,Individual,Manual,1st Owner
103,Bajaj Dominar 400,2017,1.45,1.60,1200,Petrol,Individual,Manual,1st Owner
104,Royal Enfield Classic 350,2017,1.35,1.47,4100,Petrol,Individual,Manual,1st Owner

In [54]:
# i want  2016 petrol cars & km driven less than 15 k

In [59]:
data[ (data['Year'] == 2016) & (data['Kms_Driven'] < 15000) & (data['Fuel_Type'] == 'Petrol') ]

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
38,alto k10,2016,3.00,3.76,10079,Petrol,Dealer,Manual,1st Owner
69,corolla altis,2016,14.25,20.91,12000,Petrol,Dealer,Manual,1st Owner
100,Royal Enfield Thunder 500,2016,1.75,1.90,3000,Petrol,Individual,Manual,1st Owner
110,KTM RC200,2016,1.20,1.78,6000,Petrol,Individual,Manual,1st Owner
111,Royal Enfield Thunder 350,2016,1.15,1.50,8700,Petrol,Individual,Manual,1st Owner
120,Bajaj Pulsar RS200,2016,1.05,1.26,5700,Petrol,Individual,Manual,1st Owner
122,Royal Enfield Bullet 350,2016,1.05,1.17,6000,Petrol,Individual,Manual,1st Owner
127,Bajaj Avenger 150,2016,0.75,0.80,7000,Petrol,Individual,Manual,1st Owner
133,Bajaj Avenger 220,2016,0.72,0.95,500,Petrol,Individual,Manual,1st Owner
164,Hero Splender iSmart,2016,0.45,0.54,14000,Petrol,Individual,Manual,1st Owner
165,Activa 3g,2016,0.45,0.54,500,Petrol,Individual,Automatic,1st Owner
166,Hero Passion Pro,2016,0.45,0.55,1000,Petrol,Individual,Manual,1st Owner
205,grand i10,2016,5.25,5.70,3493,Petrol,Dealer,Manual,1st Owner
216,eon,2016,2.90,4.43,12500,Petrol,Dealer,Manual,1st Owner
236,eon,2016,3.10,4.43,11849,Petrol,Dealer,Manual,1st Owner
243,i20,2016,6.25,7.60,7000,Petrol,Dealer,Manual,1st Owner
261,brio,2016,5.50,5.97,5600,Petrol,Dealer,Manual,1st Owner
278,jazz,2016,6.00,8.40,4000,Petrol,Dealer,Manual,1st Owner
283,city,2016,8.99,11.80,9010,Petrol,Dealer,Manual,1st Owner
289,city,2016,10.11,13.60,10980,Petrol,Dealer,Manual,1st Owner
292,jazz,2016,6.40,8.40,12000,Petrol,Dealer,Manual,1st Owner
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,1st Owner

In [60]:
data.head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,2nd Owner

In [61]:
# to display the selected columns 
data[["Car_Name" , "Year" , "Kms_Driven"]].head(5)

  Car_Name  Year  Kms_Driven
0     ritz  2014       27000
1      sx4  2013       43000
2     ciaz  2017        6900
3  wagon r  2011        5200
4    swift  2014       42450

In [64]:
# Check filter and selected columns
data[(data["Year"] == 2014) & (data['Kms_Driven'] < 15000) & (data['Fuel_Type'] == 'Petrol')][["Car_Name" , "Year" , "Kms_Driven"]].head(5)

                Car_Name  Year  Kms_Driven
112        KTM 390 Duke   2014        7000
154        Yamaha Fazer   2014        8000
172  Bajaj Pulsar 135 LS  2014       13700

In [65]:
data[(data["Year"] == 2014)][["Car_Name" , "Year" , "Kms_Driven"]].head(5)

    Car_Name  Year  Kms_Driven
0       ritz  2014       27000
4      swift  2014       42450
23  alto k10  2014       45280
32     swift  2014       39000
33    ertiga  2014       45000

In [11]:
data.head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,2nd Owner

In [12]:
data[data['Year']==2012][["Car_Name"]].count()

Car_Name    23
dtype: int64

In [13]:
data[data['Year']==2013][["Car_Name"]].count()

Car_Name    33
dtype: int64

In [14]:
data[data['Year']==2014][["Car_Name"]].count()

Car_Name    38
dtype: int64

In [15]:
data[data['Year']==2015][["Car_Name"]].count()

Car_Name    61
dtype: int64

In [16]:
data['Year'].unique()

array([2014, 2013, 2017, 2011, 2018, 2015, 2016, 2009, 2010, 2012, 2003,
       2008, 2006, 2005, 2004, 2007])

In [17]:
data['Year'].nunique()

16

In [18]:
data.groupby("Year")[["Car_Name"]].count()

      Car_Name
Year
2003         2
2004         1
2005         4
2006         4
2007         2
2008         7
2009         6
2010        15
2011        19
2012        23
2013        33
2014        38
2015        61
2016        50
2017        35
2018         1

In [19]:
# show me the years which is having more than 30 cars

In [20]:
data.groupby("Year")[["Car_Name"]].count().query("Car_Name > 30")

      Car_Name
Year
2013        33
2014        38
2015        61
2016        50
2017        35