In [1]:
import pandas as pd
import time

In [2]:
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\Car_Data.csv")

In [3]:
data.head(10)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,2nd Owner
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,2nd Owner
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,2nd Owner
7,s cross,2015,6.50,8.61,33429,Diesel,Dealer,Manual,2nd Owner
8,ciaz,2016,8.75,8.89,20273,Diesel,Dealer,Manual,2nd Owner
9,ciaz,2015,7.45,8.92,42367,Diesel,Dealer,Manual,2nd Owner

In [9]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
start_time = time.time()
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\accepted_2007_to_2018Q4.csv")   #1.55GB of Data
end_time = time.time()
execution_time = end_time - start_time
print(f"Time Taken to run/load the data: {execution_time} seconds")

C:\Users\DELL\AppData\Local\Temp\ipykernel_3252\2202921116.py:2: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\accepted_2007_to_2018Q4.csv")   #1.55GB of Data

In [ ]:
start_time = time.time()
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\AI_DATA_ENGINEERING\\Data_Sets\\accepted_2007_to_2018Q4.csv")   #1.55GB of Data
end_time = time.time()
execution_time = end_time - start_time
print(f"Time Taken to run/load the data: {execution_time} seconds")

In [10]:
data.shape

(301, 9)

In [11]:
data.dtypes

Car_Name          object
Year               int64
Selling_Price    float64
Present_Price    float64
Kms_Driven         int64
Fuel_Type         object
Seller_Type       object
Transmission      object
Car_Owner         object
dtype: object

In [13]:
list(data.columns)

['Car_Name',
 'Year',
 'Selling_Price',
 'Present_Price',
 'Kms_Driven',
 'Fuel_Type',
 'Seller_Type',
 'Transmission',
 'Car_Owner']

In [14]:
data[["Car_Name","Year"]].head(5)   # selected columns

  Car_Name  Year
0     ritz  2014
1      sx4  2013
2     ciaz  2017
3  wagon r  2011
4    swift  2014

In [17]:
data[data['Fuel_Type'] == 'Petrol'].head(5)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,1st Owner
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,1st Owner
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,1st Owner
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,2nd Owner
10,alto 800,2017,2.85,3.60,2135,Petrol,Dealer,Manual,2nd Owner

In [19]:
data[data['Fuel_Type'] == 'Petrol'][["Car_Name" , "Year","Selling_Price" ,"Present_Price"]].head(5)

    Car_Name  Year  Selling_Price  Present_Price
0       ritz  2014           3.35           5.59
2       ciaz  2017           7.25           9.85
3    wagon r  2011           2.85           4.15
6       ciaz  2015           6.75           8.12
10  alto 800  2017           2.85           3.60

In [20]:
data[(data['Fuel_Type'] == 'Petrol') & (data['Transmission'] == 'Automatic')].head(5) # applying two filters

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Car_Owner
12,ciaz,2015,7.50,9.94,15000,Petrol,Dealer,Automatic,2nd Owner
22,sx4,2011,4.40,8.01,50000,Petrol,Dealer,Automatic,1st Owner
40,baleno,2016,5.85,7.87,24524,Petrol,Dealer,Automatic,1st Owner
45,ciaz,2014,7.50,12.04,15000,Petrol,Dealer,Automatic,1st Owner
49,ciaz,2017,7.75,9.29,37000,Petrol,Dealer,Automatic,1st Owner

In [ ]:
# count for every year

In [22]:
data[data['Year'] == 2014][["Car_Name"]].count()

Car_Name    38
dtype: int64

In [23]:
data[data['Year'] == 2015][["Car_Name"]].count()

Car_Name    61
dtype: int64

In [24]:
data[data['Year'] == 2016][["Car_Name"]].count()

Car_Name    50
dtype: int64

In [25]:
data.groupby("Year")[["Car_Name"]].count()

      Car_Name
Year
2003         2
2004         1
2005         4
2006         4
2007         2
2008         7
2009         6
2010        15
2011        19
2012        23
2013        33
2014        38
2015        61
2016        50
2017        35
2018         1

In [28]:
data.groupby(["Year" , "Fuel_Type"])[["Car_Name"]].count().reset_index()

    Year Fuel_Type  Car_Name
0   2003    Petrol         2
1   2004    Petrol         1
2   2005    Diesel         1
3   2005    Petrol         3
4   2006    Petrol         4
5   2007    Petrol         2
6   2008    Petrol         7
7   2009    Petrol         6
8   2010    Diesel         4
9   2010    Petrol        11
10  2011       CNG         1
11  2011    Diesel         1
12  2011    Petrol        17
13  2012    Diesel         7
14  2012    Petrol        16
15  2013    Diesel         5
16  2013    Petrol        28
17  2014    Diesel        14
18  2014    Petrol        24
19  2015       CNG         1
20  2015    Diesel        15
21  2015    Petrol        45
22  2016    Diesel         8
23  2016    Petrol        42
24  2017    Diesel         4
25  2017    Petrol        31
26  2018    Diesel         1